### PR TITLE
Update haproxy chart to latest release

### PR DESCRIPTION
**Pull request by andrewheberle**
This PR updates the HAProxy ingress controller from 1.43 to 1.12.1

### CODE REVIEW

**Comment by PennyScissors** [comment]
Hello @andrewheberle, I noticed there are other haproxy charts in our Helm 2 charts catalog repository, which would need to be maintained as well. Are you intending to maintain the haproxy charts in this repo now on? If that's the case, please let me know and I'll help you deprecate the other charts so users with existing installations of those older versions aren't affected, and only the newest versions from this repo are available for new installations.

Helm 2 catalog: https://github.com/rancher/charts/tree/master/charts/haproxy

**Comment by PennyScissors** [comment]
In that case, my recommendation would be to submit a PR to that repo to add the constraint `rancher_max_version: 2.5.6` at the top of the `questions.yaml` of each chart. This will hide those older charts for users of Rancher versions greater than 2.5.6 and effectively deprecate them without affecting existing installations.

**Comment by andrewheberle** [comment]
A PR has been submitted to the other chart repo as suggested.

**Comment by andrewheberle** [comment]
Hi @PennyScissors, thanks for merging the pre-requisite changes to the older chart repo. 

Is this one now ok to merge?

**Review by PennyScissors — APPROVED** [review]

**Pull request merged**
