### PR TITLE
NGINX Service Mesh chart v1.3.1

### PR DESCRIPTION
**Pull request by pammecrandall**
- k3s not supported
- if deploying on RKE, mtls.persistentStorage should be 'off'

### CODE REVIEW

**Review by alex-isv — APPROVED** [review]
approved

**Review by alex-isv — CHANGES_REQUESTED** [review]
Due to unexpected changes from upstream our validation was failing. Looks like your PR was created during that time. We fixed the issue but you need to revert back and sync with Rancher branches again. Make sure that git status is clean before commits. You need to have 2 commits at the end.

Thanks

**Comment by samuelattwood** [comment]
You may be able to rectify this issue by running 'Fetch and merge' in your fork of main-source to pull in the fix and re-trigger validation. This should automatically update this PR. Apologies for the inconvenience.

Thanks,
Sam

**Comment by pammecrandall** [comment]
No problem at all.  I just appreciate your help.  I'll give that a try.

**Comment by pammecrandall** [comment]
I ran 'Fetch and merge' in my fork of main-source but it didn't re-trigger the validation so I ran it again in my fork pammecrandall:nsm-chart branch.  I'm not sure this fixes the problem.  It looks like github needs an approval to run the workflow.  I can just create a new PR from a new fork if this doesn't work.

**Comment by samuelattwood** [comment]
Thanks for the update. It did re-trigger validation, it just didn't execute until the PR was re-approved.

Approved. Will merge as soon as Alex's 'Changes requested' flag is removed.

**Review by samuelattwood — APPROVED** [review]

**Review by alex-isv — APPROVED** [review]

**Comment by pammecrandall** [comment]
Thank you!

**Pull request merged**
