### PR TITLE
Add percona server mongodb operator 1.13.0

### PR DESCRIPTION
**Pull request by nmarukovich**

### CODE REVIEW

**Comment by nmarukovich** [comment]
@alex-isv could you please review?

**Comment by samuelattwood** [comment]
Hey @nmarukovich Apologies for the long delay.

We are currently rolling out a new process that tracks upstream Helm repos and automatically pulls updates daily. I have created a PR, #562, based on this process for the two charts you are submitting here.

Let me know if you have any questions or concerns, otherwise I can go ahead and merge that PR. Thanks!

~ Sam

**Comment by nmarukovich** [comment]
> 

If I understand correctly all new operator versions will be pull automatically and we don't need any extra steps to do? 
What if I want to add our another operators?

**Comment by samuelattwood** [comment]
Correct, we will track releases to your repo without any additional input. If you would like to add additional charts you can create a new file inside `packages/percona/<chart name>/upstream.yaml` in the same format as the `upstream.yaml` I have submitted for these two charts. You can then submit a PR with those files.

I will be updating this repo's README for this process very soon, but you can see the process and `upstream.yaml` variables [here](https://github.com/samuelattwood/partner-charts-ci).

**Comment by samuelattwood** [comment]
@nmarukovich I'm going to close this PR out as your charts have been merged as of #562. Feel free to reach out if you have any further questions. Thanks!

**Pull request closed without merging**
