### PR TITLE
(Trilio) TrilioVault for Kubernetes Operator Release Update v2.5.0

### PR DESCRIPTION
**Pull request by bhagirathhapse**
This PR consists of:

1. URL change in package.yaml for 2.5.0 release update
2. Annotations for partner, package-name and display-name in Chart.yaml
3. Newly generated Chart.yaml.patch file
4. Newly generate assets/ charts/ directories.

### CODE REVIEW

**Comment by alex-isv** [comment]
Hi @bhagirathhapse

I tested your chart and it was deployed, however I got the following warning >

image

Can you clarify if that is expected?

**Comment by bhagirathhapse** [comment]
@alex-isv Yes, these are expected msgs and they don't impact the installation or working of the update package. So I think, we are good to go.

**Review by alex-isv — APPROVED** [review]
Verified

**Review by PennyScissors — APPROVED** [review]
lgtm

**Pull request merged**
