### PR TITLE
Add Kubecost eks cost monitoring support

### PR DESCRIPTION
**Pull request by linhlam-kc**
Resubmit the PR to add support for the AWS optimized package.
cc @atrendafilov per our offline discussion

### CODE REVIEW

**Comment by nflondo** [comment]
Hi @linhlam-kc The workflow process changed recently (a few months ago) and we migrated Kubecost to the new workflow for you.  Now the correct location for questions.yaml file is 
`packages/<vendor>/<chart>/overlay `directory. It looks like one exists there already along with a app-readme.md:
https://github.com/rancher/partner-charts/blob/main-source/packages/kubecost/cost-analyzer/overlay/questions.yaml

To update questions.yaml (and app-readme.md if needed) please follow the [new workflow](https://github.com/rancher/partner-charts#workflow), but only change applicable file(s) and send us a new PR.

Let us know if you have any questions.

HTH

**Comment by linhlam-kc** [comment]
@nflondo  Thank you ! I have update the correct question.yaml file in the latest commit https://github.com/rancher/partner-charts/pull/746/commits/a1f1a2ae5a7db7e56c6d0d153da89c214fa43947

**Comment by nflondo** [comment]
> @nflondo Thank you ! I have update the correct question.yaml file in the latest commit [a1f1a2a](https://github.com/rancher/partner-charts/commit/a1f1a2ae5a7db7e56c6d0d153da89c214fa43947)

Yw! Our CI validate is failing, so please remove questions.yaml from `charts/kubecost/cost-analyzer/questions.yaml`  and ensure no other changes were made to the partner-charts repo in your PR
Thank you !

**Comment by linhlam-kc** [comment]
@nflondo Something is messed up in my old branch so I create new branch instead with the proper changes only here https://github.com/rancher/partner-charts/pull/747 
Closing this PR

**Pull request closed without merging**
