### PR TITLE
(Citrix) adding citrix-cpx-istio-sidecar-injector chart

### PR DESCRIPTION
**Pull request by ajeetas**

### CODE REVIEW

**Comment by ajeetas** [comment]
Can you please review the changes?

Regards,
Ajeeta shakeet

**Review by PennyScissors — CHANGES_REQUESTED** [review]
Hello @ajeetas, this PR is adding a standard Helm chart, and it should be adding a package instead. Please refer to our guide [here](https://github.com/rancher/partner-charts/tree/main-source#readme) that explains the new process and workflow to add a package, and what's expected in the PR. Thanks

**Comment by ajeetas** [comment]
I have updated the new PR for this chart, closing it.
Thanks,
Ajeeta

**Comment by ajeetas** [comment]
I have updated the new PR for this chart, closing it.
Thanks,
Ajeeta

**Pull request closed without merging**
