### PR TITLE
Adding MinIO chart (v4.4.17)

### PR DESCRIPTION
**Pull request by dvaldivia**
This PR adds the MinIO Operator chart, following the guideline of the main readme.

### CODE REVIEW

**Comment by samuelattwood** [comment]
Hi @dvaldivia,
Thanks for the submission. Please add the required chart annotations as well as a `kubeVersion` variable and we should be good to merge. The recommended way to do this is, after you run `make prepare`, `packages/minio/charts` will be created. You can edit your `Chart.yaml` (or anything else) in this directory, and when you run `make patch` a patch file will be generated with any changes you've made. This allows for altering the chart without having to change your upstream.

The added variables should look something like this:
```
annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Minio Operator
  catalog.cattle.io/release-name: minio-operator
kubeVersion: '>=1.19.0-0'
```

Let me know if there is anything I can clarify. Thanks

**Comment by dvaldivia** [comment]
@samuelattwood I think the update is complete, let me know if this is correct

**Comment by samuelattwood** [comment]
Hey @dvaldivia thanks for the update. I did overlook that your chart name is just set to `operator` and it looks like something is a bit off with the `index.yaml` in this commit. The following should get this where we want it, starting from the current state. Other than editing the name variable you should be able to just copy-paste this:

```bash
export PACKAGE=minio
git reset HEAD^^
make prepare
# Edit `name` to `minio-operator` in packages/minio/charts/Chart.yaml
make patch
make clean
git add packages/minio
git commit -m "MinIO V4.4.17"
git checkout index.yaml
git clean -d -f
make charts
git add index.yaml assets charts
git commit --amend --no-edit
git push -f origin main-source
```
Thanks

**Comment by dvaldivia** [comment]
I fixed the `index.yml` problem @samuelattwood , as for the name of the chart, that is the name of our upstream chart since we offer two charts `operator` and `tenant`

**Comment by samuelattwood** [comment]
Hey @dvaldivia I understand that `operator` is your upstream chart name, my concern is that this results in Minio's chart being listed under the key `operator` in the `index.yaml` which is not ideal in a multi-vendor repository. Do you have concerns with changing the name via the patch file as I proposed above?

It also looks like the recent portworx 2.9.1 entry is duplicated in your `index.yaml`. You should not need to do any manual alteration of the `index.yaml` or resolve any merge conflicts. If you want to pull in updates from upstream a rebase should give you an easier time and avoid conflicts.

Let me know if there is any way I can help. Thanks

**Comment by dvaldivia** [comment]
@samuelattwood no problem renaming to `minio-operator` for this partner chart alone, however I do see `make charts` keep adding the old `operator` key on the `index.yaml` so I simply didn't send that, I also resetted the index.yml, please let me know if there's anything else

**Comment by samuelattwood** [comment]
Hey @dvaldivia I'm not quite sure what's going on with your duplicates there, but it's an easy fix and everything we need looks to be in place in your `packages/minio` directory. This will revert to before your commit and recreate with the standard process:
```
git clone -b adding-minio-chart https://github.com/dvaldivia/partner-charts.git
cd partner-charts
git reset HEAD^
export PACKAGE=minio
git add packages/minio
git commit -m "Make patch - minio"
git clean -d -f
git checkout index.yaml
make charts
git add index.yaml assets charts
git commit -m "Make charts - minio"
git push -f origin adding-minio-chart
```

**Comment by dvaldivia** [comment]
@samuelattwood I did as suggested, the PR is updated, I don't see a problem with the `index.yml`

**Review by samuelattwood — APPROVED** [review]
Looks good. Tested on RKE2 1.23.6 with Rancher 2.6.5. Approved.

**Pull request merged**
