### PR TITLE
Add universal-crossplane 1.5.1001

### PR DESCRIPTION
**Pull request by muvaf**

### CODE REVIEW

**Review by alex-isv — DISMISSED** [review]
Approved.

image

**Comment by samuelattwood** [comment]
@muvaf Whenever you're ready, please resolve the merge conflict here as you did with 1.4.1, and we will get this PR merged as well. Thanks!

**Comment by muvaf** [comment]
@samuelattwood done!

**Review by samuelattwood — APPROVED** [review]
Approved.

**Pull request merged**
