### PR TITLE
Update Kasten K10 Chart version to 5.0.5

### PR DESCRIPTION
**Pull request by akankshakumari393**
Update K10 Chart to 5.0.5

### CODE REVIEW

**Comment by akankshakumari393** [comment]
Hey @samuelattwood, We prepared a new chart with k10 version 5.0.5.
I am running `make validate` target after `make charts` to make sure everything is correct. But the validation fails on the `hpe-flexvolume-driver` chart.

```
WARN[0232] The following charts and assets exist in main but do not exist in your current branch.
 M assets/hpe-flexvolume-driver/hpe-flexvolume-driver-3.1.1.tgz
 M charts/hpe-flexvolume-driver/hpe-flexvolume-driver/3.1.000/Chart.yaml
 M charts/hpe-flexvolume-driver/hpe-flexvolume-driver/3.1.1/Chart.yaml
 M assets/hpe-flexvolume-driver/hpe-flexvolume-driver-3.1.000.tgz 
FATA[0232] Please commit these changes and run validation again. 
make: *** [Makefile:8: validate] Error 1
```
Is this an expected behavior out of `make validate`?

**Comment by akankshakumari393** [comment]
I have updated the PR with latest changes in `main-source` branch and the CI has passed. ✅

**Review by samuelattwood — APPROVED** [review]
Approved.

**Comment by samuelattwood** [comment]
@akankshakumari393 The initial error you encountered was due to a merged PR that had not yet being merged into `main`. Sorry for any confusion.

**Pull request merged**
