### PR TITLE
Migrating Kasten K10 chart

### PR DESCRIPTION
**Pull request by nflondo**

### CODE REVIEW

**Comment by akankshakumari393** [comment]
Hey @nflondo Thanks for the PR, I was looking into the migration process, could you please explain me why did we add this commit [https://github.com/rancher/partner-charts/pull/630/commits/1324ccdf05b546d9fa1c9001b5a73149028b86a3](https://github.com/rancher/partner-charts/pull/630/commits/1324ccdf05b546d9fa1c9001b5a73149028b86a3) I did not find this in [migration steps ](https://github.com/rancher/partner-charts#migrate-existing-chart-to-automated-updates)

**Comment by nflondo** [comment]
> Hey @nflondo Thanks for the PR, I was looking into the migration process, could you please explain me why did we add this commit [1324ccd](https://github.com/rancher/partner-charts/commit/1324ccdf05b546d9fa1c9001b5a73149028b86a3) I did not find this in [migration steps ](https://github.com/rancher/partner-charts#migrate-existing-chart-to-automated-updates)

Hi @akankshakumari393, Kasten/k10 chart is one of the "featured" charts in the Rancher Apps UI (carousel), however I had to manually add the feature flag to latest version due to a bug we had in our tool.  We've fixed that bug in the tool since then.  
(More information about our feature flag here: https://github.com/nflondo/partner-charts-ci#featuring-or-hiding-a-chart)

If PR#630 looks good to you we could proceed with that or feel free to follow Migration steps yourself and send us a new PR.
Thanks !

**Comment by akankshakumari393** [comment]
> If this PR https://github.com/rancher/partner-charts/pull/630 looks good to you we could proceed with that or feel free to follow Migration steps yourself and send us a new PR.

I tried to follow migration steps and raise a new PR. But because our latest release is 5.5.4 so in `index.yaml`, we don't have version `5.5.2` and `5.5.3` listed in `index.yaml`.  I am assuming this would mean these releases would be skipped. Is there a way we can include 5.5.2 and 5.5.3 as well?


>Kasten/k10 chart is one of the "featured" charts in the Rancher Apps UI (carousel), however I had to manually add the feature flag to latest version due to a bug we had in our tool. We've fixed that bug in the tool since then.
(More information about our feature flag here: https://github.com/nflondo/partner-charts-ci#featuring-or-hiding-a-chart)

To make it available under featured chart, do we have to follow additional steps after raising the Migration PR?

**Comment by akankshakumari393** [comment]
@nflondo any inputs on these [queries](https://github.com/rancher/partner-charts/pull/630#issuecomment-1411545348). Thanks!

**Comment by nflondo** [comment]
> I tried to follow migration steps and raise a new PR. But because our latest release is 5.5.4 so in `index.yaml`, we don't have version `5.5.2` and `5.5.3` listed in `index.yaml`. I am assuming this would mean these releases would be skipped. Is there a way we can include 5.5.2 and 5.5.3 as well?

Good catch.  In your situation, our new tool has an option to get all newer charts than available in partner-charts.  To enable this option add "fetch: newer" to your upstream.yaml e.g.

```
PackageVersion: 01
fetch: newer
ChartMetadata:
```

The above would be part of [step 3 Create an upstream.yaml...](https://github.com/rancher/partner-charts#3-create-an-upstreamyaml-in-packagescompanychart-eg), so this needs to happen on a "clean" branch (before running
`bin/partner-charts-ci stage `for example) if you have already ran partner-charts-ci and downloaded the latest version of your chart, then clean up/remove all those changes in your branch by running:
`bin/partner-charts-ci unstage` and then start from step 2 of Migration.

> To make it available under featured chart, do we have to follow additional steps after raising the Migration PR?

With regards to the feature flag for your chart, first please remove all existing feature flags for k10:
`bin/partner-charts-ci feature remove kasten/k10` then ensure the line `catalog.cattle.io/featured: "1"` is removed for all versions of k10 in `index.yaml`, if not manually remove it.  Next, re-add feature flag to kasten/10:
`bin/partner-charts-ci feature add kasten/k10 1`
Featuring your chart steps above could be done towards the end of your migration steps, before step 9 commiting your changes.
HTH

**Comment by akankshakumari393** [comment]
Hi @nflondo, Thanks for the help. I have raised a new PR [https://github.com/rancher/partner-charts/pull/658](https://github.com/rancher/partner-charts/pull/658) for migrating Kasten K10 chart. It also adds feature annotation. Please take a look at it.

Also, Can we close this PR #630 now since it skips `5.5.3` version from [index](https://github.com/rancher/partner-charts/pull/630/files#diff-08c65c1b5ef8384ef0200558777c52f4110afcbbacc880ac5375d555ca97ee3e).

Thanks!

**Comment by nflondo** [comment]
Closing.  PR #658 was merged instead of this one.

**Pull request closed without merging**
