### PR TITLE
Upgrade InAccel FPGA Operator

### PR DESCRIPTION
**Pull request by eliaskoromilas**
InAccel [[fpga-operator-2.6.1](https://artifacthub.io/packages/helm/inaccel/fpga-operator/2.6.1)] Helm chart

### CODE REVIEW

**Review by alex-isv — CHANGES_REQUESTED** [review]
I can see error from validate:
image

Please review your last commit and run #make validate and make sure no errors.

**Comment by eliaskoromilas** [comment]
> I can see error from validate: image
> 
> Please review your last commit and run #make validate and make sure no errors.

I did that before opening this PR and it passed. Now, I can see the same issue on my end, too.

But anyway, I only committed changes under `assets/fpga-operator/*`, `charts/fpga-operator/*` and `packages/fpga-operator/*`. How could my commits make `citrix-adc-istio-ingress-gateway` chart validation fail?

I also checked `upstream` and it fails there too:

```
❯ git clone -b main-source https://github.com/rancher/partner-charts
Cloning into 'partner-charts'...
remote: Enumerating objects: 6044, done.
remote: Counting objects: 100% (1421/1421), done.
remote: Compressing objects: 100% (649/649), done.
remote: Total 6044 (delta 979), reused 831 (delta 764), pack-reused 4623
Receiving objects: 100% (6044/6044), 9.08 MiB | 601.00 KiB/s, done.
Resolving deltas: 100% (2787/2787), done.

❯ make -C partner-charts validate
make: Entering directory 'partner-charts'
Pulling in charts-build-scripts version https://github.com/rancher/charts-build-scripts.git@v0.2.2
./scripts/pull-scripts: line 28: warning: command substitution: ignored null byte in input
charts-build-scripts => ./bin/charts-build-scripts
charts-build-scripts version v0.2.2 (e11e8fb)
INFO[0000] Generating charts and checking if Git is clean 
INFO[0000] Pulling https://datawire-static-files.s3.amazonaws.com/charts/ambassador-6.7.11.tgz from upstream into charts 
INFO[0002] Loading dependencies for chart               
INFO[0002] Applying changes from generated-changes      
INFO[0002] Applying: generated-changes/patch/Chart.yaml.patch 
INFO[0002] Adding: charts/app-readme.md                 
INFO[0002] Adding: charts/questions.yml                 
INFO[0002] Generated archive: assets/ambassador/ambassador-6.7.1100.tgz 
INFO[0002] Generated chart: charts/ambassador/ambassador/6.7.1100 
INFO[0002] Pulling https://charts.jfrog.io/artifactory-ha-4.13.0.tgz from upstream into charts 
INFO[0004] Loading dependencies for chart               
INFO[0004] Found chart options for postgresql in generated-changes/dependencies/postgresql/dependency.yaml 
INFO[0004] Pulling https://charts.bitnami.com/bitnami/postgresql-9.3.4.tgz from upstream into charts 
INFO[0005] Updating chart metadata with dependencies    
INFO[0005] Applying changes from generated-changes      
INFO[0005] Applying: generated-changes/patch/Chart.yaml.patch 
INFO[0005] Adding: charts/app-readme.md                 
INFO[0005] Adding: charts/questions.yml                 
INFO[0005] Generated archive: assets/artifactory-ha/artifactory-ha-4.13.1.tgz 
INFO[0005] Generated chart: charts/artifactory-ha/artifactory-ha/4.13.1 
INFO[0005] Pulling https://charts.jfrog.io/artifactory-jcr-3.4.0.tgz from upstream into charts 
INFO[0006] Loading dependencies for chart               
INFO[0006] Found chart options for artifactory in generated-changes/dependencies/artifactory/dependency.yaml 
INFO[0006] Pulling https://charts.jfrog.io/artifactory/api/helm/jfrog-charts/artifactory-11.7.4.tgz from upstream into charts 
INFO[0006] Updating chart metadata with dependencies    
INFO[0006] Applying changes from generated-changes      
INFO[0006] Applying: generated-changes/patch/Chart.yaml.patch 
INFO[0006] Adding: charts/app-readme.md                 
INFO[0006] Adding: charts/questions.yml                 
INFO[0006] Generated archive: assets/artifactory-jcr/artifactory-jcr-3.4.1.tgz 
INFO[0006] Generated chart: charts/artifactory-jcr/artifactory-jcr/3.4.1 
INFO[0007] Pulling https://storage.googleapis.com/triggermesh-charts/aws-event-sources-0.1.9.tgz from upstream into charts 
INFO[0007] Loading dependencies for chart               
INFO[0007] Applying changes from generated-changes      
INFO[0007] Applying: generated-changes/patch/Chart.yaml.patch 
INFO[0007] Adding: charts/app-readme.md                 
INFO[0007] Adding: charts/questions.yml                 
INFO[0007] Generated archive: assets/aws-event-sources/aws-event-sources-0.1.901.tgz 
INFO[0007] Generated chart: charts/aws-event-sources/aws-event-sources/0.1.901 
INFO[0007] Pulling https://citrix.github.io/citrix-helm-charts/citrix-adc-istio-ingress-gateway-1.11.0.tgz from upstream into charts 
INFO[0008] Loading dependencies for chart               
INFO[0008] Applying changes from generated-changes      
INFO[0008] Applying: generated-changes/patch/Chart.yaml.patch 
ERRO[0008] 
patching file Chart.yaml
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file Chart.yaml.rej 
FATA[0008] Encountered error while trying to prepare package: Encountered error while preparing main chart: Encountered error while trying to apply changes to charts: Unable to generate patch with error: exit status 1 
make: *** [Makefile:8: validate] Error 1
make: Leaving directory 'partner-charts'
```

The test looks pretty flaky to me (taking into account that this morning it was passing). I recall facing similar behavior while testing my previous PR.

**Comment by eliaskoromilas** [comment]
It seems that I validated my changes before rebasing and that is why I saw it passing.

I fixed the `citrix-adc-istio-ingress-gateway` and `citrix-cpx-istio-sidecar-injector` patch issues.

**Comment by eliaskoromilas** [comment]
Indeed the upstream charts were modified yesterday (https://github.com/citrix/citrix-helm-charts/pull/105) and that is why the old patches failed.

I think upstream should probably release new versions instead of [patching](https://github.com/citrix/citrix-helm-charts/commit/cbbe78f8e608e2f5393a17416ca5fe9a3d986f33) existing ones.

**Review by alex-isv — CHANGES_REQUESTED** [review]
Please clean your old commits and keep only last 2 per PR. Make sure that git status is clean before you'll make any changes.
Even though it was deployed fine on my rke cluster, you need to keep only 1 asset per PR as currently you have 3 in 1. (I'm assuming you just did it by mistake)
image

**Comment by eliaskoromilas** [comment]
To be honest, I don't really care about the failing charts. I just want to update `fpga-operator`.

CI was failing due to `citrix-*` upstream changes and my last 2 commits fix that. I am not responsible for the failing charts. Should we contact the respective partner to review this afterall?

**Comment by alex-isv** [comment]
Looks like Citrix made changes upsteam which they should not do. We are checking with them.

**Review by samuelattwood — APPROVED** [review]
Apologies for the issue with the Citrix charts. We appreciate the PR you submitted to help rectify their problem.

Format looks good, test install ran cleanly. Approved.

**Review by alex-isv — APPROVED** [review]

**Pull request merged**
