### PR TITLE
add Percona Operator for MySQL based on Percona XtraDB Cluster

### PR DESCRIPTION
**Pull request by nmarukovich**
Signed-off-by: Natalia Marukovich <natalia.marukovich@percona.com>

### CODE REVIEW

**Comment by nmarukovich** [comment]
@samuelattwood hi! Could you have alook on this PR?

**Comment by nflondo** [comment]
Hi @nmarukovich Do you want both charts to be named the same in the Rancher Catalog? "Percona Operator for MySQL based on Percona XtraDB Cluster"  Also, the name seems a bit long and it may get cut off in the UI.

**Comment by nmarukovich** [comment]
> Hi @nmarukovich We don't allow two charts to have the same name in the Rancher Catalog: "Percona Operator for MySQL based on Percona XtraDB Cluster" Also, the name seems a bit long and it may get cut off in the UI.

ok. So I need create separate catalog for new operator?

**Comment by nflondo** [comment]
No, you only need to change the "DisplayName:" in your upstream.yaml files to make the name of each chart unique (and shorter preferably).  Right now, both charts have the same long name and it looks like this in the Rancher catalog:
percona-new

**Comment by nmarukovich** [comment]
> No, you only need to change the "DisplayName:" in your upstream.yaml files to make the name of each chart unique (and shorter preferably). Right now, both charts have the same long name and it looks like this in Rancher Apps: percona-new

O! Thanks! Fixed! 
Unfortunately I can't make the name of operator shorter and we need to use 
Percona Operator For MySQL based on Percona XtraDB Cluster 
because we also have operator for mysql.

**Comment by nmarukovich** [comment]
@nflondo could you please recheck it?

**Review by nflondo — APPROVED** [review]
Approved

**Pull request merged**
