### PR TITLE
Dynatrace oneagent operator v0.10.2 release

### PR DESCRIPTION
**Pull request by 0sewa0**
~currently make `validate` is failing. But running it never reaches this chart, it always fails during the validation of another chart.~

### CODE REVIEW

**Review by alex-isv — CHANGES_REQUESTED** [review]
Your chart.yaml is missing annotation: catalog.cattle.io/display-name: (should be in capital)
Missing kubeVersion: "1.18 - 1.21"
charts should not be inside packages
Please review the workflow -> https://github.com/rancher/partner-charts#workflow
After making all changes make sure that you have only 2 commits in your PR.

**Comment by 0sewa0** [comment]
@alex-isv hopefully its good now :)

**Review by alex-isv — CHANGES_REQUESTED** [review]
Due to unexpected changes from upstream our validation was failing. Looks like your PR was created during that time. We fixed the issue but you need to revert back and sync with Rancher branches again. Make sure that git status is clean before commits. You need to have 2 commits at the end.

Thanks

**Comment by samuelattwood** [comment]
You may be able to rectify this issue by running 'Fetch and merge' in your fork of main-source to pull in the fix and re-trigger validation. This should automatically update this PR. Apologies for the inconvenience.

Thanks,
Sam

**Review by alex-isv — APPROVED** [review]
tested on RKE

**Review by alex-isv — COMMENTED** [review]
Can you please remove Chart.yaml.orig from packages > generated changes as it's not supposed to be commited.
image

Thanks

**Comment by 0sewa0** [comment]
> Can you please remove Chart.yaml.orig from packages > generated changes as it's not supposed to be commited. image
> 
> Thanks
@alex-isv 
https://github.com/rancher/partner-charts/pull/266

**Pull request merged**
