### PR TITLE
(Trilio) TrilioVault for Kubernetes Operator Release Update v2.5.2

### PR DESCRIPTION
**Pull request by bhagirathhapse**
This PR consists of:
1. URL change in package.yaml for 2.5.2 release update
2. Annotations for partner, package-name and display-name in Chart.yaml
3. Newly generated Chart.yaml.patch file
4. Newly generate assets/ charts/ directories.

### CODE REVIEW

**Comment by bhagirathhapse** [comment]
@alex-isv I agree that I should be validating it at our end before raising the PR. I am able to install the package without any issue locally since the build we use it `2.5.2` whereas when I have generated rancher partner chart, it became `2.5.200` which is not present on our repository. This is causing the installation to stuck/hang.
Here is the logline showing that version update due to rancher chart generation to `2.5.200` is causing this issue:

`021/10/07 07:44:50 error downloading chart error finding the Chart URL: chart "k8s-triliovault-operator" version "2.5.200" not found in https://charts.k8strilio.net/trilio-stable/k8s-triliovault-operator repository
panic: error downloading chart error finding the Chart URL: chart "k8s-triliovault-operator" version "2.5.200" not found in https://charts.k8strilio.net/trilio-stable/k8s-triliovault-operator repository
`

If the version would not be updated with concatenating `00` to the product release version `2.5.0` it would work fine.
Let me know if there is anything we can do. Once this issue is resolved, I will close this PR and created new one with only 2 commits.

For 2.5.0, I am able to install the build on Rancher server and there is not issue:

```
helm install --namespace=default --timeout=10m0s --values=/home/shell/helm/values-k8s-triliovault-operator-2.5.0.yaml --version=2.5.0 --wait=true k8s-triliovault-operator /home/shell/helm/k8s-triliovault-operator-2.5.0.tgz
--
Fri, Oct 8 2021 12:08:55 pm | creating 1 resource(s)
Fri, Oct 8 2021 12:08:56 pm | creating 9 resource(s)
Fri, Oct 8 2021 12:08:56 pm | beginning wait for 9 resources with timeout of 10m0s
Fri, Oct 8 2021 12:08:58 pm | Deployment is not ready: default/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Fri, Oct 8 2021 12:09:00 pm | Deployment is not ready: default/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Fri, Oct 8 2021 12:09:02 pm | Deployment is not ready: default/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Fri, Oct 8 2021 12:09:04 pm | Deployment is not ready: default/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Fri, Oct 8 2021 12:09:06 pm | Deployment is not ready: default/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Fri, Oct 8 2021 12:09:08 pm | Deployment is not ready: default/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Fri, Oct 8 2021 12:09:10 pm | Deployment is not ready: default/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Fri, Oct 8 2021 12:09:12 pm | NAME: k8s-triliovault-operator
Fri, Oct 8 2021 12:09:12 pm | LAST DEPLOYED: Fri Oct 8 16:08:55 2021
Fri, Oct 8 2021 12:09:12 pm | NAMESPACE: default
Fri, Oct 8 2021 12:09:12 pm | STATUS: deployed
Fri, Oct 8 2021 12:09:12 pm | REVISION: 1
Fri, Oct 8 2021 12:09:12 pm | TEST SUITE: None
Fri, Oct 8 2021 12:09:12 pm | NOTES:
Fri, Oct 8 2021 12:09:12 pm | To verify that TrilioVault Operator has started, run:
Fri, Oct 8 2021 12:09:12 pm |  
Fri, Oct 8 2021 12:09:12 pm | kubectl --namespace=default get deployments -l "release=k8s-triliovault-operator"
Fri, Oct 8 2021 12:09:12 pm |  
Fri, Oct 8 2021 12:09:12 pm | ---------------------------------------------------------------------
Fri, Oct 8 2021 12:09:12 pm | SUCCESS: helm install --namespace=default --timeout=10m0s --values=/home/shell/helm/values-k8s-triliovault-operator-2.5.0.yaml --version=2.5.0 --wait=true k8s-triliovault-operator /home/shell/helm/k8s-triliovault-operator-2.5.0.tgz
Fri, Oct 8 2021 12:09:12 pm | ---------------------------------------------------------------------
```

**Comment by alex-isv** [comment]
Please read our example -> 

https://github.com/rancher/partner-charts/tree/main-source#2-set-up-your-package-to-track-an-upstream-chart-skip-if-upgrading-existing-package

packageVersion will add that 00 to your generated asset
So, if in your package.yaml you had  url: https://example.com/helm-repo/chart-0.1.2.tgz
and packageVersion: 01
you'll get an asset with the name chart-0.1.201.tgz and this is what basically happened in your example.
I checked other charts with similar versions and they all adding 00 to the asset if packageVersion defined as 00, and deployed with no issues.

**Comment by alex-isv** [comment]
@bhagirathhapse 
Please change line packageVersion:
to 01 not 00
update and commit and that should solve the problem

**Comment by alex-isv** [comment]
@bhagirathhapse 
I just tested your older verion 2.0.500 on k3s and rke and it was installed with no problems
I'm assuming that last 00 was added from your packageVersion numbers.
Also, you cannot have more than one asset in your chart and your index.yaml should match your chart.yaml or you'll get an error ->  cannot find it.

**Comment by alex-isv** [comment]
> @alex-isv Yes the same chart I was talking about. We have implemented this behavior from `v2.5.0`. Now, here is my question: We had same tag present in `values.yaml` for 2.5.0 and in `package_version: 00`, then how come the asset and chart for `2.5.0` was created with name `2.5.0` and NOT as `2.5.000` ? My expectation is same for `2.5.2` as well, that the partner chart code should create asset and chart with version `2.5.2` and NOT by appending `package_version: 00` making it `2.5.200` which causing problem for us. This triggered me in thinking that something has changed on Rancher side which has created assets as `2.5.200`

Please review prereq -> https://github.com/rancher/partner-charts/tree/main-source#2-set-up-your-package-to-track-an-upstream-chart-skip-if-upgrading-existing-package
The formula is used -> int(patchVersion*100 + packageVerison)
Also, Rancher is forcing you to have a valid semver. So, if you have version 2.5.2 and a packageVersion: 01, the asset will be changed to 2.5.201

**Comment by bhagirathhapse** [comment]
Things are pretty messed up in this PR and we are still trying to resolve the issue at our end for `tag` field that it used to construct the image name.
I am closing this PR and test everything at our end and create a new pull request with validated code.

**Pull request closed without merging**
