### PR TITLE
(Trilio) TrilioVault for Kubernetes Operator Release Update v2.6.3

### PR DESCRIPTION
**Pull request by bhagirathhapse**
This PR consists of:
1. URL change in package.yaml for 2.6.3 release update
2. Annotations for partner, package-name, and display-name in Chart.yaml
3. Newly generated Chart.yaml.patch file
4. Newly generated assets/ and charts/ directories.

Partner chart is validated against the RKE cluster:

image

image

### CODE REVIEW

**Comment by samuelattwood** [comment]
@bhagirathhapse I'm running into an issue with the webhook-init container, where it is failing to access the `MutatingWebhookConfiguration` resource from `admissionregistration.k8s.io/v1beta1`. This is due to a recent change in Kubernetes 1.22, `admissionregistration.k8s.io/v1beta1` no longer serves this resource, as it has been available via `admissionregistration.k8s.io/v1` since 1.16

**Comment by bhagirathhapse** [comment]
Thank you, @samuelattwood!
As per our discussion over slack, I have updated the `kubeVersion: 1.18-1.21`, and code changes are pushed. Please validate and approve if all is good.

**Comment by samuelattwood** [comment]
Hey @bhagirathhapse. Thanks for the update. It looks like the `kubeVersion` change didn't make its way into the `index.yaml` which could happen if `make charts` is run twice without a change in the chart version.

Typically, rather than trying to fix the generated files after running `make charts`, we prefer to just create a fresh pair of commits and replace the originals with a force push.

**Comment by bhagirathhapse** [comment]
@samuelattwood Yesterday night, we have released the new patch v2.6.4 to fix some of the customer-facing issues. It also includes the fix for install on k8s 1.22.
To keep the PR for partner charts clean, I will be closing this PR and creating a new PR for 2.6.4.

**Comment by bhagirathhapse** [comment]
New PR # https://github.com/rancher/partner-charts/pull/296

**Pull request closed without merging**
