### PR TITLE
Remove everything except assets and index

### PR DESCRIPTION
**Pull request by aiyengar2**
This PR is part of a migration to a new structure for this Github repository.

After the necessary PRs are merged, changes to the chart will be made to the `main-source` branch and, on successful push, the assets that are generated from it will be automatically committed to the `main` branch.

This PR needs to be merged before https://github.com/rancher/partner-charts/pull/39.

### CODE REVIEW

**Comment by aiyengar2** [comment]
@StrongMonkey will the charts/ and sha256sum/ directories automatically get generated when https://github.com/rancher/partner-charts/pull/39 is merged?

**Comment by StrongMonkey** [comment]
@aiyengar2 yes it will

**Comment by aiyengar2** [comment]
> @aiyengar2 yes it will

Nice

@cbron once you review, we should merge this PR in before we merge https://github.com/rancher/partner-charts/pull/39.

**Review by StrongMonkey — APPROVED** [review]

**Review by cbron — APPROVED** [review]
lgtm., but wait to merge until 39 is ready, just in case.

**Comment by aiyengar2** [comment]
https://github.com/rancher/partner-charts/pull/39 is ready to go

**Pull request merged**
