### PR TITLE
Shipa 1.6.3 release

### PR DESCRIPTION
**Pull request by ravilach**
Howdy SUSE Rancher Buds, time for our monthly maintenance release. Thanks!

Installed 1.6.3 via Rancher. 

image

### CODE REVIEW

**Comment by samuelattwood** [comment]
@ravilach It looks like your ingress values have moved from `service.nginx` to `shipaCluster.ingress`. Two of the values in your `questions.yaml` were impacted by this and should be updated to match. Other than that everything should be good to go.

**Comment by ravilach** [comment]
Thanks for the heads up and check. Made some edits and re-upload the questions and TAR. 

image

**Comment by ravilach** [comment]
Commmitted

**Review by samuelattwood — APPROVED** [review]
Thanks for the update.

Looks good. Tested on k3s 1.22.7 and k3s 1.22.5 Approved.

**Pull request merged**
