### PR TITLE
feat(gluu): add Gluu partner chart

### PR DESCRIPTION
**Pull request by moabu**
# Adding Gluu Partner Chart

## Description

This PR adds Gluu official chart to rancher ui partner charts. During the creation of this PR we reported an [issue](https://github.com/rancher/partner-charts/issues/235) regarding using dashed keys inside `questions.yaml`. 

## Type of change

- [x] New Chart (non-breaking change which adds functionality)

## How Has This Been Tested?

- [x] Followed instructions regarding testing, using a docker based rancher ui setup. 

**Test Configuration**:
OS Ubuntu 20 LTS with docker 20.10. 7 and rancher 2.6.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings during validation
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by fxHouard** [comment]
Hi, I am SUSE's point of contact for Gluu, don't hesitate to get to me should you need anything!

Best regards

**Comment by samuelattwood** [comment]
Hi,
It looks like you've added the catalog.cattle.io annotations to your upstream chart's Chart.yaml. Functionally this is fine, and if you want to leave it this way you may, but because they are Rancher-specific they are typically handled via the patch file mechanism. This allows them to be managed directly in this repo without having to alter your upstream.

I was able to run a successful test deployment on k3s using the opendj backend and openebs.io/local for PV provisioner. It did look like the gluu-opendj-backup pod was failing to startup correctly, but that is more likely something to do with the image rather than the helm chart.

```
INFO - jans.pycloudlib.wait - 2021-11-10 19:09:21,950 - Config is ready
INFO - jans.pycloudlib.wait - 2021-11-10 19:09:21,967 - Secret is ready
python3: can't open file '/app/scripts/entrypoint.py': [Errno 2] No such file or directory
ERROR:  The detected Java version could not be used with the set of Java
arguments -server -XX:+UseContainerSupport -XX:MaxRAMPercentage= .
The detected Java binary is: /usr/bin/java
You must specify the path to a valid Java 7 or higher version.
The procedure to follow is to set the environment variable OPENDJ_JAVA_HOME
to the root of a valid Java 7 installation.
If you want to have specific Java settings for each command line you must
edit the properties file specifying the Java binary and/or the Java arguments
for each command line.  The Java properties file is located in:
/opt/opendj/config/java.properties.
```

**Comment by moabu** [comment]
hey @samuelattwood ,

Thanks for testing. As for the annotations, we added it upstream on purpose. We have other integrations we are working on and as we post these it will help as an indicator as well as for automation. If we find it unnecessary later we will add it to the patch process.

As it goes for the error, it does look like the image was changed actually.  The helm chart itself doesn't seem to be the problem. I just noticed that the `questions.yaml` was defaulting to the wrong image.

**Comment by samuelattwood** [comment]
Hi @moabu,
Thank you for the update, your changes look good and the new default tag appears to have resolved the issue. We typically try to stick to a 2 commit PR to ensure the correct generation process was followed. If possible, please close out this PR and open a fresh one with the standard two commits, and it will be approved and merged. Thanks.

**Comment by moabu** [comment]
@samuelattwood new PR https://github.com/rancher/partner-charts/pull/245.

**Pull request closed without merging**
