### PR TITLE
Neuvector: Updating NeuVector chart version to 2.4.0

### PR DESCRIPTION
**Pull request by selvamt94**

### CODE REVIEW

**Comment by selvamt94** [comment]
@samuelattwood Can you please review this  PR.

**Comment by nflondo** [comment]
> @samuelattwood Can you please review this PR.
Hi @selvamt94 Sorry for the delay.  Samuel is no longer with SUSE/Rancher, but he implemented automation to chart updates.  To take advantage of this new automation going forward, you may migrate Neuvector by following the steps here: https://github.com/nflondo/partner-charts/tree/nmc-readme#migrate-existing-chart-to-automated-updates
Thanks.

**Comment by selvamt94** [comment]
@nflondo We have decided not to update the partner chart since NeuVector can deployed from feature chart . We have also an instruction on the partner chart how to migrate to feature chart. We will work on publishing again partner chart if there is a request  from the customer for partner chart. Thanks.

**Comment by nflondo** [comment]
@selvamt94 ok.  It sounds like customers should install NeuVector from feature chart going forward? How much longer will NeuVector from partner chart be supported? Thanks.

**Comment by selvamt94** [comment]
@nflondo Yes, SSO is supported if NeuVector is deployed from feature chart. We recommend to use feature chart if Rancher manager version 2.6.5 and above used. Customer may only need partner chart if they are running older Rancher. We have not received any request to update partner chart recently, so we want to wait and see if any request comes.

**Comment by nflondo** [comment]
> @nflondo Yes, SSO is supported if NeuVector is deployed from feature chart. We recommend to use feature chart if Rancher manager version 2.6.5 and above used. Customer may only need partner chart if they are running older Rancher. We have not received any request to update partner chart recently, so we want to wait and see if any request comes.

Hello @selvamt94, Since Neuvector chart in Partner Catalog has not been updated in 9 months (since Nov 1, 2022), would it be ok with you guys if we remove it from Partner Catalog?
Regards.

**Comment by selvamt94** [comment]
@nflondo Yes we can remove Neuvector from Partner Catalog. We made a request to remove NeuVector from Partner Catalog on a slack channel, forgot which one. 

Thanks 
Selvam.

**Comment by nflondo** [comment]
@selvamt94 YW. We'll remove it from Partner Catalog then.  You can reach our team via [#discuss-partner-product-certifications](https://suse.slack.com/archives/C03K5TKAKAT) slack channel
Regards.

**Pull request closed without merging**
