### PR TITLE
Add nats server chart

### PR DESCRIPTION
**Pull request by boxboatmatt**
Add nats server chart

### CODE REVIEW

**Review by alex-isv — CHANGES_REQUESTED** [review]
You need to test deployment from Rancher on your side first to make sure it's working.
I cannot deploy it neither on k3s nor on rke. It's showing > 
image


No yaml is available for edit and nothing from your question.yaml is visible.
Please review and test it first.

**Comment by boxboatmatt** [comment]
> You need to test deployment from Rancher on your side first to make sure it's working. I cannot deploy it neither on k3s nor on rke. It's showing > image
> 
> No yaml is available for edit and nothing from your question.yaml is visible. Please review and test it first.

I addressed the issue where the `index.yaml` was incorrect - helm install works properly now... However I can't get rancher to show the Chart in the Apps & Marketplace UI for some reason.

**Comment by alex-isv** [comment]
Now it's working, but you need to review the workflow on how to test -> https://github.com/rancher/partner-charts#7-test-your-changes
Basically from your local partner-chart directory checkout your branch and open http server as > python3 -m http.server 8000
from the 2nd terminal run > ngrok http 8000
Create a test repo on Rancher, copy Forwarding url from ngrok to your test-repo on Rancher and you should be able to see your icon from the Rancher marketplace. Usually you need to perform test from your local Rancher on k3s and rke and make sure it deployed with no issues before opening a PR.

**Review by alex-isv — APPROVED** [review]
looks good

image

**Comment by boxboatmatt** [comment]
> Now it's working, but you need to review the workflow on how to test -> https://github.com/rancher/partner-charts#7-test-your-changes
> Basically from your local partner-chart directory checkout your branch and open http server as > python3 -m http.server 8000
> from the 2nd terminal run > ngrok http 8000
> Create a test repo on Rancher, copy Forwarding url from ngrok to your test-repo on Rancher and you should be able to see your icon from the Rancher marketplace. Usually you need to perform test from your local Rancher on k3s and rke and make sure it deployed with no issues before opening a PR.

Thanks... that is what I ended up doing to get it to work. For some reason it just wouldn't show up from my GitHub fork

**Comment by boxboatmatt** [comment]
@wallyqs @ColinSullivan1 - PR is ready to ship

**Comment by ColinSullivan1** [comment]
@boxboatmatt , thank you for the contribution!

**Pull request merged**
