### PR TITLE
Minor updates to CloudCasa listing

### PR DESCRIPTION
**Pull request by bobadair**
Update CloudCasa description and display name.

### CODE REVIEW

**Comment by bobadair** [comment]
I also noticed that CI does not seem to be pulling the latest version of our Helm chart from repo https://catalogicsoftware.github.io/cloudcasa-helmchart for some reason. We updated it about 2 weeks ago on 6/26, and it hasn't yet propagated over here.

**Comment by bobadair** [comment]
> I also noticed that CI does not seem to be pulling the latest version of our Helm chart from repo https://catalogicsoftware.github.io/cloudcasa-helmchart for some reason. We updated it about 2 weeks ago on 6/26, and it hasn't yet propagated over here.

This may be because the version number hadn't been updated. We've incremented the minor version number and are waiting to see if the changes get pulled in the next CI run.

**Comment by nflondo** [comment]
> > I also noticed that CI does not seem to be pulling the latest version of our Helm chart from repo https://catalogicsoftware.github.io/cloudcasa-helmchart for some reason. We updated it about 2 weeks ago on 6/26, and it hasn't yet propagated over here.
> 
> This may be because the version number hadn't been updated. We've incremented the minor version number and are waiting to see if the changes get pulled in the next CI run.

Correct.  Only new chart versions are fetched by our CI.  I will run the CI today to fetch new version right away.

**Review by nflondo — APPROVED** [review]
Approved.

**Comment by bobadair** [comment]
Thanks!

**Pull request merged**
