### PR TITLE
Add Intel Trusted Certificate Issuer

### PR DESCRIPTION
**Pull request by poussa**

### CODE REVIEW

**Comment by poussa** [comment]
@Jono-SUSE-Rancher @samuelattwood can we get reviewed, please?

**Comment by poussa** [comment]
> Let me know if you have any issues. Thanks

Thanks @samuelattwood, no issues. Hope the PR is now good.

**Comment by samuelattwood** [comment]
Hey @poussa All good except it looks like you captured the `packages/intel-tcs-issuer/charts` directory which isn't meant to be committed. Please just go ahead and remove that directory and we should be good. Thanks

**Review by samuelattwood — APPROVED** [review]
Thanks @poussa 

Approved.

**Pull request merged**
