### PR TITLE
Datawiza init partner charts

### PR DESCRIPTION
**Pull request by weiyuDatawiza**
Hi, rancher team.
This PR adds Datawiza Access Broker official chart to rancher ui partner charts.

### CODE REVIEW

**Comment by samuelattwood** [comment]
Hi @weiyuDatawiza,
Sorry for the delay. It looks like your commit includes the `packages/datawiza-access-broker/charts` directory. This directory is temporary and should get cleaned up by running `make clean` prior to your first commit.

Typically we try to run a test deployment of the chart, but it looks like it requires access to an authenticated registry. If you could provide some screenshots demonstrating successful deployment from the Rancher UI, that would be appreciated. Thanks.

**Comment by weiyuDatawiza** [comment]
@samuelattwood Thanks. 
` It looks like your commit includes the packages/datawiza-access-broker/charts directory. This directory is temporary and should get cleaned up by running make clean prior to your first commit.`
Sry for that and should I submit another PR or commit to this PR?

`Typically we try to run a test deployment of the chart, but it looks like it requires access to an authenticated registry. If you could provide some screenshots demonstrating successful deployment from the Rancher UI, that would be appreciated. Thanks.`
Sure. 
image
image
image
image
image

**Comment by weiyuDatawiza** [comment]
@samuelattwood Thanks. Have force pushed to overwrite the commits.

**Comment by weiyuDatawiza** [comment]
@samuelattwood  Hi. Can you help review the new changes? Thanks.

**Review by samuelattwood — APPROVED** [review]
Layout looks good. Test deployment confirmed with screenshots. Approved.

**Pull request merged**
