### PR TITLE
NGINX Service Mesh chart v1.6.0

### PR DESCRIPTION
**Pull request by sjberman**

### CODE REVIEW

**Comment by samuelattwood** [comment]
Hey @sjberman,
We are rolling out a new process for this repo that allows us to track partner's upstream Helm repo automatically. I went ahead and created a [migration PR](https://github.com/rancher/partner-charts/pull/560) for all 3 of the F5 charts currently in our repo, NGINX Service Mesh, NGINX Ingress Controller, and F5 BigIP Controller. The PR also includes updates for all 3 charts, including this PR's update.

With the newer process we will check your Helm repos daily for updates and merge them automatically. The only time a PR is required is to update your `questions.yaml` or `app-readme.md`, in which case you can just update the relevant file in your `packages/f5/chart-name/overlay` and commit. The changed file will be included in the next CI update.

One other note, the 'default' tag in the `questions.yaml` is optional and is always overridden by the chart's `values.yaml`. It looks like you are currently iterating the default image tag value in the `questions.yaml`. This isn't necessary since it is updated in your chart release, so I went ahead and removed that from the `questions.yaml` when I pulled it into my PR.

Let me know if you have any questions/concerns, otherwise I can go ahead and merge the migration PR. Thanks!

~ Sam

**Comment by sjberman** [comment]
@samuelattwood Thanks for the information! This sounds like it will make the process much easier for us. Go ahead with the migration PR.

**Comment by sjberman** [comment]
@samuelattwood I'm guessing the README will be updated at some point to describe this, but if we wanted to change the artifact path for testing purposes, I'm assuming that would involve updating `upstream.yaml`? And then is there a trigger to pull in that artifact to our branch?

**Comment by samuelattwood** [comment]
Hey @sjberman This release went live in #565. You are correct that the `upstream.yaml` dictates where the CI checks for updates. If you need to make any alterations you can submit a PR with edits to that file. You can see current documentation [here](https://github.com/samuelattwood/partner-charts-ci) but this repo's README will be updated soon to reflect it as well. Feel free to reach out if there is anything further I can clarify. Thanks!

**Comment by sjberman** [comment]
@samuelattwood I installed Rancher today, but I'm not seeing the latest (0.6.0) NGINX Service Mesh release show up in the marketplace.

 If there's a better forum to chat, let me know.

**Comment by samuelattwood** [comment]
@sjberman NGINX Service Mesh 0.6.0 is definitely published. A fresh install can at times take a few minutes to pull the latest releases, so perhaps you were still seeing a cached list. I can confirm that it is visible in my clusters.

In terms of a chat forum, our typical go-to is Slack. The easiest might be to reach me through the [Rancher Users](https://slack.rancher.io/) Slack.

**Pull request closed without merging**
