### PR TITLE
Nutanix CSI storage 2.5.2

### PR DESCRIPTION
**Pull request by tuxtof**

### CODE REVIEW

**Comment by samuelattwood** [comment]
@tuxtof Everything looks good and it deploys fine, but I did note that your `appVersion` is still set to `2.5.1`. Is that intended?

**Comment by tuxtof** [comment]
@samuelattwood yes it is expected driver version don't change just the chart

**Review by samuelattwood — APPROVED** [review]
Sounds good, just wanted to make sure.
Tested on RKE2 1.22.5. Approved.

**Comment by tuxtof** [comment]
Thanks for the remark

**Pull request merged**
