### PR TITLE
(Trilio) TrilioVault for Kubernetes Operator Release Update v2.5.3

### PR DESCRIPTION
**Pull request by bhagirathhapse**
This PR consists of: 
1. URL change in package.yaml for 2.5.3 release update
2. Annotations for partner, package-name and display-name in Chart.yaml
3. Newly generated Chart.yaml.patch file
4. Newly generated assets/ and charts/ directories.

### CODE REVIEW

**Comment by bhagirathhapse** [comment]
Here are the screenshots of the successful installation of the operator for the reference.
```
helm install --namespace=tvk --timeout=10m0s --values=/home/shell/helm/values-k8s-triliovault-operator-2.5.300.yaml --version=2.5.300 --wait=true k8s-triliovault-operator /home/shell/helm/k8s-triliovault-operator-2.5.300.tgz
--
Tue, Nov 2 2021 4:32:39 am | creating 1 resource(s)
Tue, Nov 2 2021 4:32:40 am | W1102 08:32:40.769601 20 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
Tue, Nov 2 2021 4:32:40 am | W1102 08:32:40.772017 20 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
Tue, Nov 2 2021 4:32:40 am | W1102 08:32:40.774316 20 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
Tue, Nov 2 2021 4:32:40 am | creating 9 resource(s)
Tue, Nov 2 2021 4:32:41 am | W1102 08:32:41.135506 20 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
Tue, Nov 2 2021 4:32:41 am | W1102 08:32:41.154192 20 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
Tue, Nov 2 2021 4:32:41 am | W1102 08:32:41.158259 20 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
Tue, Nov 2 2021 4:32:41 am | beginning wait for 9 resources with timeout of 10m0s
Tue, Nov 2 2021 4:32:41 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:32:43 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:32:45 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:32:47 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:32:49 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:32:51 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:32:53 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:32:55 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:32:57 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:32:59 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:33:01 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:33:03 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:33:05 am | Deployment is not ready: tvk/k8s-triliovault-operator. 0 out of 1 expected pods are ready
Tue, Nov 2 2021 4:33:07 am | NAME: k8s-triliovault-operator
Tue, Nov 2 2021 4:33:07 am | LAST DEPLOYED: Tue Nov 2 08:32:40 2021
Tue, Nov 2 2021 4:33:07 am | NAMESPACE: tvk
Tue, Nov 2 2021 4:33:07 am | STATUS: deployed
Tue, Nov 2 2021 4:33:07 am | REVISION: 1
Tue, Nov 2 2021 4:33:07 am | TEST SUITE: None
Tue, Nov 2 2021 4:33:07 am | NOTES:
Tue, Nov 2 2021 4:33:07 am | To verify that TrilioVault Operator has started, run:
Tue, Nov 2 2021 4:33:07 am |  
Tue, Nov 2 2021 4:33:07 am | kubectl --namespace=tvk get deployments -l "release=k8s-triliovault-operator"
Tue, Nov 2 2021 4:33:07 am |  
Tue, Nov 2 2021 4:33:07 am | ---------------------------------------------------------------------
Tue, Nov 2 2021 4:33:07 am | SUCCESS: helm install --namespace=tvk --timeout=10m0s --values=/home/shell/helm/values-k8s-triliovault-operator-2.5.300.yaml --version=2.5.300 --wait=true k8s-triliovault-operator /home/shell/helm/k8s-triliovault-operator-2.5.300.tgz
Tue, Nov 2 2021 4:33:07 am | ---------------------------------------------------------------------
```
image

**Review by samuelattwood — APPROVED** [review]
Looks good. Test install ran cleanly.

**Review by alex-isv — APPROVED** [review]
approved

**Comment by bhagirathhapse** [comment]
@samuelattwood @alex-isv Can we merge this PR to `main-source` branch now?

**Pull request merged**
