### PR TITLE
External secrets operator 0.5.9

### PR DESCRIPTION
**Pull request by CharlKlein**
Helllos,

Please accept this PR for the Updates to increment External-Secrets-Operator to v0.5.9 :)

Sharing some awesome news, ESO has been accepted in to the CNCF Sandbox 🥳 

Tested on Rancher 2.6.4
```
NAME                                                             READY   STATUS    RESTARTS   AGE
pod/external-secrets-operator-5f5b555cdf-26z9k                   1/1     Running   0          7m20s
pod/external-secrets-operator-cert-controller-5649dc8b44-lxm74   1/1     Running   0          7m20s
pod/external-secrets-operator-webhook-5cf4c657df-8jjc9           1/1     Running   0          7m20s

NAME                                        TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/external-secrets-operator-webhook   ClusterIP   10.43.111.16   <none>        443/TCP   7m20s
service/kubernetes                          ClusterIP   10.43.0.1      <none>        443/TCP   10m

NAME                                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/external-secrets-operator                   1/1     1            1           7m20s
deployment.apps/external-secrets-operator-cert-controller   1/1     1            1           7m20s
deployment.apps/external-secrets-operator-webhook           1/1     1            1           7m20s

NAME                                                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/external-secrets-operator-5f5b555cdf                   1         1         1       7m20s
replicaset.apps/external-secrets-operator-cert-controller-5649dc8b44   1         1         1       7m20s
replicaset.apps/external-secrets-operator-webhook-5cf4c657df           1         1         1       7m20s
```

### CODE REVIEW

**Comment by samuelattwood** [comment]
Hey @CharlKlein Congratulations on acceptance to the CNCF Sandbox!

I am beginning to roll out a new configuration option for this repo, to allow us to keep charts updated from upstream without a manual PR. The goal is that a PR should only be required if you need to edit your `app-readme.md` or `questions.yaml`, and otherwise updates will be pulled automatically from your upstream Helm repo, `https://charts.external-secrets.io`.

If you have no objection, I can submit a PR on your behalf to move your chart configuration over to this setup. Let me know if you have any concerns.

Thanks!

**Comment by CharlKlein** [comment]
Hey @samuelattwood 

Thank you. 

No objections at all. A PR on the new process would be perfect. Can you tag me in it so I can see what changed so I can communicate with my team accordingly 

Cheers

**Comment by samuelattwood** [comment]
@CharlKlein I'm going to close this out, as #503 has been merged. Let me know if you have any questions. Thanks

**Comment by CharlKlein** [comment]
Great Thank you :)

**Pull request closed without merging**
