### PR TITLE
Kong branch

### PR DESCRIPTION
**Pull request by CAcquaviva**

### CODE REVIEW

**Review by alex-isv — CHANGES_REQUESTED** [review]
This is what I'm getting on my local test instance.

image

Did you test it on Rancher from your side?
Can you provide a screenshot if it's successful and clarify configuration settings for my test.

**Comment by CAcquaviva** [comment]
Keep in mind Kong plays the Ingress Controller role in your K8s cluster so, by default, it deploys with proxy.type=LoadBalancer. You can change it if you will to NodePort. Here are my screen shots

https://docs.google.com/document/d/1gQnbOk5d8WMNLeY-gHiyNyLuBouYcgX2nFqCi5scx8U/edit?usp=sharing

**Comment by CAcquaviva** [comment]
You can create an Ingress and consume it using the NodeIP and Port:

cat <<EOF | kubectl apply -f -
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress1
  namespace: sampleapp
  annotations:
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
        - path: /ingress1
          backend:
            serviceName: sampleservice
            servicePort: 5000
EOF


http 172.17.0.3:32662/ingress1

where 172.17.0.3 is the NodeIP and 32662 is the NodePort

$ kubectl get node -o wide
NAME         STATUS   ROLES                  AGE   VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                              KERNEL-VERSION   CONTAINER-RUNTIME
local-node   Ready    control-plane,master   40m   v1.21.3+k3s1   172.17.0.3    <none>        SUSE Linux Enterprise Server 15 SP3   5.4.0-1045-aws   containerd://1.4.8-k3s1

$ kubectl get service --all-namespaces
NAMESPACE             NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
cattle-fleet-system   gitjob            ClusterIP   10.43.148.182   <none>        80/TCP                       39m
cattle-system         rancher           ClusterIP   10.43.224.122   <none>        443/TCP                      40m
cattle-system         rancher-webhook   ClusterIP   10.43.186.182   <none>        443/TCP                      39m
cattle-system         webhook-service   ClusterIP   10.43.132.71    <none>        443/TCP                      39m
default               kong-kong-proxy   NodePort    10.43.192.106   <none>        80:32662/TCP,443:31828/TCP   16m
default               kubernetes        ClusterIP   10.43.0.1       <none>        443/TCP                      40m
kube-system           kube-dns          ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       40m
sampleapp             sampleservice     ClusterIP   10.43.142.233   <none>        5000/TCP

**Review by alex-isv — APPROVED** [review]

**Review by PennyScissors — APPROVED** [review]
lgtm. Leaving it as approved until we are ready to merge and release.

**Pull request merged**
