### PR TITLE
Updated to OpenEBS v2.10.0 latest release chart

### PR DESCRIPTION
**Pull request by is-ashish**
Updated latest version v2.10.0 openebs.

Signed-off-by: ashishjain <ashish.jain@mayadata.io>

### CODE REVIEW

**Comment by nareshdesh** [comment]
We have raised PR in helm3 and helm2 too.
 Helm3: https://github.com/rancher/helm3-charts/pull/69
 Helm2: https://github.com/rancher/charts/pull/1342

**Comment by PennyScissors** [comment]
Hello @nareshdesh and @is-ashish, this PR does not add a package as it is suppose to, instead it adds a standard helm chart. Please refer to our documentation [here](https://github.com/rancher/partner-charts/tree/main-source#readme) to understand the workflow to add a package. As for the other issues, I'll be closing them out since we are no longer accepting new charts in them. All future PRs should be made to this repository. Thank you!

**Review by PennyScissors — CHANGES_REQUESTED** [review]
Hello @nareshdesh and @is-ashish, this PR does not add a package as it is suppose to, instead it adds a standard helm chart. Please refer to our documentation [here](https://github.com/rancher/partner-charts/tree/main-source#readme) to understand the workflow to add a package. As for the other issues, I'll be closing them out since we are no longer accepting new charts in those repositories. All future PRs should be made to this repository. Thank you!

**Comment by is-ashish** [comment]
Closing this PR, Now we will go with OpenEBS 2.11.0 latest released chart. 

Have raised PR [PR-117](https://github.com/rancher/partner-charts/pull/117).
cc: @nareshdesh

**Pull request closed without merging**
