### PR TITLE
Add px essentials 2.9.1

### PR DESCRIPTION
**Pull request by dahuang-purestorage**
adding portworx-essentials 2.9.1 (free tier of portworx enterprise)

### CODE REVIEW

**Comment by dahuang-purestorage** [comment]
@samuelattwood review welcome

**Comment by dahuang-purestorage** [comment]
@alex-isv @samuelattwood any update on this? let me know if there's any issue i can help to resolve.

**Comment by dahuang-purestorage** [comment]
@alex-isv @samuelattwood friendly check-in on this PR. anything i can do to move this PR forward?

**Comment by samuelattwood** [comment]
Hey @dahuang-purestorage Apologies for the delay on this. The PR looks good and I have successfully tested on RKE2 1.23.6 with Rancher 2.6.5.

One small suggestion I'd make is to set your kubeVersion to `>=1.16.0-0` to ensure the chart does not get filtered for EKS and GKE versions since they mark their builds using a dash, which SemVer2 interprets as a prerelease flag and Helm will filter without the added `-0`. Other than that we should be all set to merge. Thanks

**Comment by dahuang-purestorage** [comment]
thanks @samuelattwood , do you mean in the index.yaml, Charts, and patch files?

**Comment by samuelattwood** [comment]
@dahuang-purestorage There are few ways you could do it, but I would just amend the patch file and recreate the second commit

```
export PACKAGE=portworx-essentials
git reset HEAD^

## Edit packages/portworx-essentials/generated-changes/patch/Chart.yaml.patch and update the `kubeVersion`

git add packages/portworx-essentials
git commit --amend --no-edit
git checkout index.yaml
git clean -d -f
make charts
git add index.yaml assets charts
git commit -m "Make charts"
git push -f origin main-source
```

**Comment by dahuang-purestorage** [comment]
@samuelattwood updated!

**Review by samuelattwood — APPROVED** [review]
Thanks for the update :slightly_smiling_face:

Approved.

**Pull request merged**
