### PR TITLE
feat(janssen): update janssen helm partner chart

### PR DESCRIPTION
**Pull request by mo-auto**
# Creating Janssen Partner Chart

This is an automated PR triggered by a release in [Janssen](https://github.com/JanssenProject/jans) charts.

## Description

This PR updates the Janssen official chart to rancher ui partner charts.  We reported an [issue](https://github.com/rancher/partner-charts/issues/235) regarding using dashed keys inside `questions.yaml`. 

## Type of change

- [x] Update Chart (non-breaking change which adds functionality)

## How Has This Been Tested?

- [x] Followed instructions regarding testing, using a docker based rancher ui setup. 

**Test Configuration**:
OS Ubuntu 20 LTS with docker 20.10. 7 and rancher 2.6.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings during validation
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by samuelattwood** [comment]
Hi @mo-auto, to clarify, is this intended to be a discrete chart from the existing Gluu chart?

**Comment by moabu** [comment]
Hey @samuelattwood ,

@mo-auto is just my bot. Anyways, this is a chart for janssen project which is the base of Gluu 5.x. Gluu 5.x has a couple more proprietary services. Janssen is a different project so it needs to be fully available under its own chart

https://github.com/JanssenProject/jans

vs

Gluu flex
https://github.com/GluuFederation/flex

**Comment by samuelattwood** [comment]
Hey @moabu Thanks, I figured as much just wanted to confirm.

I ran into a couple issues deploying the chart. I'm deploying using `opendj` and initially was using `kubernetes.io/aws-ebs` for pv provisioning. It looks like the storage class defaults to `IO1` for EBS which requires IOPs to be defined, but it didn't seem to define that value. The opendj image also failed to pull because the default tag of `1.0.0_dev` doesn't exist for `gluufederation/opendj`. I changed this to `5.0.0_dev` which seemed to work. Lastly, for whatever reason the scim pod seemed to just repeatedly crash, I didn't dig too much into that one, it was outputting suppressed Java exceptions, then would say `Server:main: Started Server` then would shutdown shortly thereafter.

If I deployed with the corrected opendj tag, Longhorn as provisioner, and scim disabled, the chart deployed fine.

**Comment by samuelattwood** [comment]
@moabu Sounds good, thanks. I will close this PR for now.

**Pull request closed without merging**
