### PR TITLE
universal-crossplane: add v1.5.2001

### PR DESCRIPTION
**Pull request by hasheddan**
Adds universal-crossplane v1.5.2001.

### CODE REVIEW

**Comment by samuelattwood** [comment]
@hasheddan Since we've merged #353, feel free to rebase whenever convenient and we will get the remaining two merged. Thanks

**Comment by samuelattwood** [comment]
@hasheddan Just wanted to check in on this. I am prepared to merge once you have rebased.

**Comment by hasheddan** [comment]
@samuelattwood apologies for the delay here! I have rebased and will follow with a rebase on https://github.com/rancher/partner-charts/pull/355 once this is merged 👍🏻

**Review by samuelattwood — APPROVED** [review]
Thanks for the update. Tested on RKE 1.22.7 with Rancher 2.6.4. Approved.

**Pull request merged**
