### PR TITLE
citrix-adc-istio-ingress-gateway to version 1.11.0

### PR DESCRIPTION
**Pull request by ajeetas**

### CODE REVIEW

**Comment by ajeetas** [comment]
ingress-rancher2
Please review changes.
Thanks,
Ajeeta

**Review by alex-isv — COMMENTED** [review]
Hi @ajeetas ,
I'm getting the following error during the installation >>

image


Did you test it from your side?
My test is from the local single node. I need a clarification on setup. Do you require any specific configuration?

**Comment by ajeetas** [comment]
Hi @alex-isv alex-isv

Prerequisite:
1. Please enable/install istio service mesh.

There are two ways to deploy this chart 
1. When ingress-gateway ADC is CPX
    1. Need to set arguments 
        1. Set citrixCPX to true in Deployment settings  Deployment Settings
        2. accept `EULA` license to true in ingressGateway Settings
        3. Set Ingress gateway nodePortrequired to true  in  ingressGateway Settings
2. When ingress-gateway ADC is VPX
    1. Need to set arguments 
        1. Set citrixCPX to false in Deployment settings  Deployment Settings
        2. accept `EULA` license to true in ingressGateway Settings
        3. Set Ingress gateway netscalerUrl with ADC nsip and vserverIP with VIP of ADC  in ingressGateway Settings
	
You can try the first approach to deploy it. 
For detailed information, you can check this [blog](https://rancher.com/blog/2020/deploying-citrix-adc-service-mesh-rancher)
Please let mee know, if you have any query.

Thanks,
Ajeeta

**Review by alex-isv — APPROVED** [review]
Validated.

**Comment by ajeetas** [comment]
Hi All,

Sorry for the inconvenience, because of minor changes I have created another PR for the same charts.
Please look into that:
https://github.com/rancher/partner-charts/pull/167

Regards,
Ajeeeta

**Comment by alex-isv** [comment]
Closing.
New PR -> #167

**Pull request closed without merging**
