### PR TITLE
Adding DxEnteprise to marketplace

### PR DESCRIPTION
**Pull request by ian-buse**
Hello Samuel and Rancher team,

We would like to add DH2i DxEnterprise to the marketplace as a new partner. Please let us know if there are any issues!

### CODE REVIEW

**Comment by samuelattwood** [comment]
Hey @ian-buse
We are currently rolling out a new process that allows us to track a partner's upstream helm or git repo and pull in updates automatically. I went ahead and created a PR, #563, for your chart - tracking https://raw.githubusercontent.com/dh2i/dxe/main/index.yaml. Your repo will be queried daily for updates. Let me know if you have any questions/concerns, otherwise I can go ahead and merge that PR.

Two quick suggestions I wanted to make. It might be useful to link to your [documentation](https://support.dh2i.com/docs/category/guides/dxenterprise/containers/kubernetes) in either the `README.md` or `app-readme.md`. You also could alter your `questions.yaml` such that the EULA acceptance is just a check box or a `Y/N` drop-down. There are more details on `questions.yaml` options in our [docs](https://docs.ranchermanager.rancher.io/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps#question-variable-reference).

~ Sam

**Comment by ian-buse** [comment]
Hi @samuelattwood

Thank you for the recommendations! I have updated the upstream chart's `questions.yml` and `README.md` to reflect those changes. Since Rancher is tracking the upstream chart, I take it that means we do not need to run patches to update our chart? Should I do anything else from here? If not, I'm ready to merge.

Regards,

Ian

**Comment by samuelattwood** [comment]
Hey @ian-buse Thanks for the quick update, that looks great. You are correct, we will track your releases automatically - so nothing else is required. I will also mention, while you are more than welcome to include the `catalog.cattle.io` annotations in your upstream as you do now, you aren't required to and our CI will add them automatically if not present.

I will proceed with merging on the new process. Thanks!

~ Sam

**Comment by samuelattwood** [comment]
I'm going to close this out as your chart has been merged as of #567. Please reach out if there is anything I can clarify further. Thanks!

~ Sam

**Pull request closed without merging**
