### PR TITLE
Update px 2.10.3

### PR DESCRIPTION
**Pull request by dahuang-purestorage**

### CODE REVIEW

**Comment by dahuang-purestorage** [comment]
@samuelattwood  review welcome.

**Comment by samuelattwood** [comment]
Hey @dahuang-purestorage Apologies for the delay.

I am beginning to roll out a new configuration option for this repo, to allow us to keep charts updated from upstream without a manual PR. It looks like currently you are essentially maintaining a dedicated Helm repo for Rancher, so I can set a new configuration to pull from the repo at `https://raw.githubusercontent.com/portworx/charts-rancher/master/stable/index.yaml` for both the Portworx chart and the Portworx Essentials chart.

If you are alright with this, I can submit a PR to migrate the config on your behalf, and this repo will then track changes to your `portworx/charts-rancher` repo. Let me know if you would like me to do this, or if you have any questions/concerns.

Thanks

**Comment by dahuang-purestorage** [comment]
@samuelattwood hey, that sounds good to me. thanks for doing this!

**Comment by samuelattwood** [comment]
@dahuang-purestorage I'm going to close this out as #504 has been merged. As mentioned there, let me know if you have any questions. Thanks

**Comment by dahuang-purestorage** [comment]
Hey @samuelattwood, thanks! I have a few questions. After the upstream automation, I don't need to make a PR to this branch as i did for the past few ones, but just update my helm charts, right? 
If so, how often does partner-charts pull from our repository? 
Thanks!

**Comment by samuelattwood** [comment]
@dahuang-purestorage Correct, and the check runs daily. It is currently pointed at the master branch of your `charts-rancher` repo, using the Helm repo index, so the monitored repo file is: https://raw.githubusercontent.com/portworx/charts-rancher/master/stable/index.yaml

If you would ever like to change the repo being tracked just let us know.

**Comment by dahuang-purestorage** [comment]
@samuelattwood  I have a new version released for portworx and portworx-essentials yesterday. Where can I check the CI job that monitors the version? If that's not available, when can I expect it to be released?

**Comment by samuelattwood** [comment]
Hey @dahuang-purestorage, the update was merged in #559 and released in #565. Normally you can expect an update same or next-day. I just had a few other additions I was trying to include in the same push which delayed it slightly.

**Pull request closed without merging**
