### PR TITLE
Upgrade Portworx 2.8.1

### PR DESCRIPTION
**Pull request by dahuang-purestorage**
currently `make validate` is failing. But running it on main-source is also failing. Might be a bug on the upstream branch.

### CODE REVIEW

**Comment by dahuang-purestorage** [comment]
@alex-isv review welcomed.

**Comment by alex-isv** [comment]
Yes, looks like one of the upstream was changed so validation is failing. We are checking with affected partner to fix that.

**Review by alex-isv — CHANGES_REQUESTED** [review]
Due to unexpected changes from upstream our validation was failing. Looks like your PR was created during that time. We fixed the issue but you need to revert back and sync with Rancher branches again. Make sure that git status is clean before commits. You need to have 2 commits at the end.

Thanks

**Comment by samuelattwood** [comment]
Hi,
You may be able to rectify this issue by simply running 'Fetch and merge' in your fork of main-source to pull in the fix and re-trigger validation. This should automatically update this PR. Apologies for the inconvenience.

Thanks,
Sam

**Comment by dahuang-purestorage** [comment]
@alex-isv finished rebasing on master. review welcome :) thanks!

**Comment by samuelattwood** [comment]
Hi @dahuang-purestorage, apologies for the delay. While attempted to deploy this chart, I ran into a couple things I wanted to inquire about. For background, typically we test charts on k3s, RKE, and/or RKE2 running on SUSE Linux Enterprise 15 SP3.

First, k3s and RKE2 appear to encounter issues due to the location of the containerd socket `/run/k3s/containerd/containerd.sock` vs the default `/run/containerd/containerd.sock`.

Second, on RKE with a Docker backend, it finds the socket as expected, but fails due to the `px-fuse` kernel module missing. Digging in to this it looks like you provide builds [here](https://mirrors.portworx.com/build-results/pxfuse/for-installer/x86_64/) for kernels matching past SLES kernel versions up to 15 SP2 (5.3.18-24) but not SP3 (5.3.18-59).   I was curious if it would be possible to offer a build for that kernel version.

**Comment by dahuang-purestorage** [comment]
Hey @alex-isv. Thanks for the update. We are looking into the fix for those. Meanwhile, is there a workaround we can do to merge the changes that we have? Thanks.

**Comment by dahuang-purestorage** [comment]
Hi @samuelattwood 
I've updated the charts to accommodates the containerd socket for k3s and rke2. 

for the px-fuse kernel. We will have SP3 (5.3.18-59) kernel available  in our next release. Unfortunately, we don't have one at the moment. 

Let me know if there's more issues with the charts. Thanks!

**Comment by samuelattwood** [comment]
Hi @dahuang-purestorage
Thank you for the update. Unfortunately when I try to deploy to k3s, the `stork-scheduler` pods enter a crash loop due to `Error: unknown flag: --scheduler-name`. Let me know if this is due to a configuration option I am overlooking.

I have been able to successfully deploy to a traditional RKE cluster with a Docker backend, on SLE15 SP2 which is kernel `5.3.18-24.96`. Considering the k3s/rke2 and SP3 kernel issues are already present in the current version of the chart as well, I will approve this chart update without these fixed, but support in the future would certainly be appreciated. Thanks!

**Comment by dahuang-purestorage** [comment]
@samuelattwood 
Thanks for raising the issue. I just put in some updates on the code that fixes the --scheduler-name issue you were seeing. 
In addition, I updated some charts to include CSI definition (it's required for installing on k3s cluster) and added some CustomResourceDefinition (also required). 
I'll let you know if we have kernel support in the future. 
Let me know if you run into any issues. Thanks!

**Comment by samuelattwood** [comment]
@dahuang-purestorage 
Thanks very much for the continued updates. I have successfully tested deployment on kernel 5.3.18-24 with RKE 1.21.6 as well as k3s 1.22.5. Approved.

**Review by samuelattwood — APPROVED** [review]

**Review by alex-isv — APPROVED** [review]

**Pull request merged**
