### PR TITLE
Portworx charts v2.8.0

### PR DESCRIPTION
**Pull request by dahuang-purestorage**
contains latest portworx charts v2.8.0. Any feedback is appreciated. thanks!

### CODE REVIEW

**Comment by harsh-px** [comment]
@PennyScissors can we help with moving this forward?

**Comment by dahuang-purestorage** [comment]
@alex-isv 
I have tried manually updating the folder to the format {VERSION}{PackageVersion}, but this would break when I run `make validate`. 

I think there are some edge case I'm running into with the `charts-build-script` or I'm missing some configuration setup. Please let me know what I can do to fix this.
Many thanks!

**Comment by alex-isv** [comment]
@dahuang-purestorage 
Looks like now, Rancher is forcing to have a valid semver. So, in your case 2.8.1 is a valid one, so you should be good.

**Comment by alex-isv** [comment]
@dahuang-purestorage 
Please clarify which parameters to use to install it from the local RKE cluster.

**Comment by dahuang-purestorage** [comment]
@alex-isv 
this is the command i use for helm3 installation:
```
helm install --debug  --namespace kube-system --set etcdType=Built-in,environment="OnPrem",onpremStorage="Automatically scan disks",usedrivesAndPartitions=true --generate-name charts/portworx/portworx/2.8.1/
```

is this what you are looking for? Is there a way we can document this in partner-charts?
thanks!

**Review by alex-isv — APPROVED** [review]
Looks good

Verified on RKE

image

**Comment by dahuang-purestorage** [comment]
@alex-isv friendly reminder, when might this be merged? Let me know if you need more info from my end. thanks!

**Pull request merged**
