### PR TITLE
Add SoftIron RBD Chart

### PR DESCRIPTION
**Pull request by dabukalam**
Signed-off-by: Danny Abukalam <danny@softiron.com>

### CODE REVIEW

**Review by alex-isv — CHANGES_REQUESTED** [review]
Hi @dabukalam 
Please review the workflow from -> https://github.com/rancher/partner-charts/tree/main-source#workflow
You need to have the same structure as in our example with asset, chart, index, etc. and you need to have 2 commits in your PR at the end with 1st commit 'changes' and 2nd commit 'make charts'
A good example should look similar to this -> 
image

**Comment by dabukalam** [comment]
@alex-isv just updated this, let me know if that's what you're looking for

**Review by alex-isv — CHANGES_REQUESTED** [review]
Hi @dabukalam 
Can you clarify steps on installation. Which setup is required in order to install it from Rancher?
Please provide detailed steps. Just remember that usually we just testing installation from the local instance and if any additional setup is needed you need to provide details on that.

**Comment by dabukalam** [comment]
@alex-isv @samuelattwood I've just pushed the changes we discussed yesterday for your review - let me know if it works your end.

**Review by samuelattwood — APPROVED** [review]
Thanks Danny

Tested on rke2 1.22.4 and k3s 1.22.4. Looks good - Approved.

**Review by alex-isv — APPROVED** [review]

**Pull request merged**
