### PR TITLE
Speedscale Operator 0.11.43

### PR DESCRIPTION
**Pull request by swtch1**
This change adds the Speedscale Operator version 0.11.43.

### CODE REVIEW

**Comment by swtch1** [comment]
Hmm, it appears I'm adding the vals-operator binary for some reason.

**Comment by samuelattwood** [comment]
@swtch1 The vals-operator validate error isn't on your end, it will be rectified shortly.

**Comment by swtch1** [comment]
Ok, well I did some git foo to remove the diff.  Let me know if we require any changes.

**Comment by samuelattwood** [comment]
@swtch1 Please run a 'Fetch and merge' on your fork of the repo to pull in the validation fix and we can proceed with merging. Thanks 

Submissions appears properly formed, cannot otherwise smoke test due to API key requirement.

**Comment by swtch1** [comment]
@samuelattwood done.  Thank you.

**Review by samuelattwood — APPROVED** [review]

**Pull request merged**
