### PR TITLE
Remove charts managed by Koor

### PR DESCRIPTION
**Pull request by galexrt**
Koor Technologies, Inc. is in the process of shutting down, see https://koor.tech/.

Please accept this PR to remove the Koor's `koor-operator` chart.

### CODE REVIEW

**Review by adamkpickering — CHANGES_REQUESTED** [review]
Thank you for the PR! I see that a few more things need to be removed:
- `packages/koor-tech/`
- `assets/koor-tech`
- References to charts managed by Koor in `index.yaml`

**Comment by galexrt** [comment]
Thanks! I have updated the PR to remove the other files and update the `index.yaml` file. PTAL

**Review by adamkpickering — APPROVED** [review]
LGTM. Thanks again :smile:

**Comment by adamkpickering** [comment]
FYI I'm going to hold off on merging this, because we are currently working on some automation and I want to avoid causing any problems with that work.

**Pull request merged**
