### PR TITLE
F5 Container Ingress Services Helm Charts v0.0.19 

### PR DESCRIPTION
**Pull request by trinaths**
F5 Container Ingress Services Helm Charts v0.0.19 for Rancher catalogue.

### CODE REVIEW

**Comment by samuelattwood** [comment]
Hi @trinaths Thanks for the submission. I have a couple things to note before merging.

There is currently no default value for `version` which causes the chart to attempt to pull `f5networks/k8s-bigip-ctlr:` which will fail due to the `:` with no following tag.

I'd recommend changing your `kubeVersion` to `'1.20.0-0 - 1.23.0-0'`. EKS and GKE don't correctly follow SemVer2 and this can cause issues with Helm version checking if you're missing the `-0`. This is a [known issue](https://github.com/helm/helm/issues/10375).

This is not required but I'd highly recommend adding even a brief `questions.yaml` to allow easy setting of important values via the Rancher UI. I wrote a short, functional example for your chart that you're welcome to use or expand upon. Users are still able to edit the values.yaml in the UI alongside this.
```
questions:
- variable: bigip_login_secret
  required: true
  type: string
  label: "BIG-IP Login Secret"
- variable: args.bigip_url
  required: true
  type: string
  label: "BIG-IP Management IP/URL"
- variable: args.bigip_partition
  required: true
  type: string
  label: "BIG-IP Partition"
- variable: image.user
  type: string
  label: "BIG-IP Image Repository"
- variable: image.repo
  type: string
  label: "BIG-IP Image"
- variable: version
  type: string
  label: "BIG-IP Version"
  default: "latest"
```

This may be due to my lack of background with BIG-IP, but it wasn't clear in the docs that the appsvcs package had to be manually installed to my BIG-IP instance for the CIS.

Let me know if there is anything I can clarify. Thanks

**Comment by trinaths** [comment]
> Hi @trinaths Thanks for the submission. I have a couple things to note before merging.
> 
> There is currently no default value for `version` which causes the chart to attempt to pull `f5networks/k8s-bigip-ctlr:` which will fail due to the `:` with no following tag.
> 
> I'd recommend changing your `kubeVersion` to `'1.20.0-0 - 1.23.0-0'`. EKS and GKE don't correctly follow SemVer2 and this can cause issues with Helm version checking if you're missing the `-0`. This is a [known issue](https://github.com/helm/helm/issues/10375).
> 
> This is not required but I'd highly recommend adding even a brief `questions.yaml` to allow easy setting of important values via the Rancher UI. I wrote a short, functional example for your chart that you're welcome to use or expand upon. Users are still able to edit the values.yaml in the UI alongside this.
> 
> ```
> questions:
> - variable: bigip_login_secret
>   required: true
>   type: string
>   label: "BIG-IP Login Secret"
> - variable: args.bigip_url
>   required: true
>   type: string
>   label: "BIG-IP Management IP/URL"
> - variable: args.bigip_partition
>   required: true
>   type: string
>   label: "BIG-IP Partition"
> - variable: image.user
>   type: string
>   label: "BIG-IP Image Repository"
> - variable: image.repo
>   type: string
>   label: "BIG-IP Image"
> - variable: version
>   type: string
>   label: "BIG-IP Version"
>   default: "latest"
> ```
> 
> This may be due to my lack of background with BIG-IP, but it wasn't clear in the docs that the appsvcs package had to be manually installed to my BIG-IP instance for the CIS.
> 
> Let me know if there is anything I can clarify. Thanks

@samuelattwood  - Updated PR with your suggestions. Please help review the PR and merge.

**Comment by trinaths** [comment]
@samuelattwood - CIS charts version is 0.0.19. However in package.yaml, I gave 01 which is attached to the generated code. Any better way to fix this ?

**Comment by samuelattwood** [comment]
@trinaths Thanks very much for the update. The `packageVersion` appended to the chart version is expected, the intention is to allow for iteration on the chart if necessary, without having to alter the upstream. Looking at where `.Chart.Version` is used, I wouldn't expect this to be problematic for your chart, do you have concerns?

It looks like you've separately modified the files in `charts/f5-container-ingress-services`. We want to make sure any chart changes are captured by the patch and overlay files in `packages/f5-container-ingress-services/generated-changes`, it ensures that the chart gzip in `assets` matches the ones in `charts`, and also helps with consistency for updates.

All the pieces are here for this to be complete, we just need to do a little bit of cleanup. If we start from the state of the current branch, this will revert to before your commits and regenerate them with the correct changes: 

```
export PACKAGE=f5-container-ingress-services
git reset c76293dd3af510e8d393392b06df348631e71a49
make prepare

##Edit packages/f5-container-ingress-services/charts/Chart.yaml and set `kubeVersion: '1.20.0-0 - 1.23.0-0'`

make patch
make clean
git add packages/f5-container-ingress-services
git commit -m "Make patch - F5"
git clean -d -f
git checkout index.yaml
make charts
git add index.yaml assets charts
git commit -m "Make charts - F5"
git push -f origin f5-charts
```

**Comment by trinaths** [comment]
@samuelattwood  - pushed a new PR as per your suggestions.

**Comment by samuelattwood** [comment]
@trinaths Found one last thing when I was testing this, the value your chart uses for the image tag is `.Values.version` not `.Values.image.version` so your new `questions.yaml` isn't setting this. If we want to just adjust the `questions.yaml` to set `.Values.version`:

```
##Edit packages/f5-container-ingress-services/generated-changes/overlay/questions.yaml
##Change `- variable: image.version` to `- variable: version`

git add packages/f5-container-ingress-services/
git commit --amend --no-edit
make charts
git add assets charts
git commit --amend --no-edit
git push -f origin f5-charts
```

**Comment by trinaths** [comment]
> @trinaths Found one last thing when I was testing this, the value your chart uses for the image tag is `.Values.version` not `.Values.image.version` so your new `questions.yaml` isn't setting this. If we want to just adjust the `questions.yaml` to set `.Values.version`:
> 
> ```
> ##Edit packages/f5-container-ingress-services/generated-changes/overlay/questions.yaml
> ##Change `- variable: image.version` to `- variable: version`
> 
> git add packages/f5-container-ingress-services/
> git commit --amend --no-edit
> make charts
> git add assets charts
> git commit --amend --no-edit
> git push -f origin f5-charts
> ```

@samuelattwood  - Done. Updated PR as per the review suggestions.

**Review by samuelattwood — APPROVED** [review]
Looks good. Tested on RKE 1.22.9 and RKE2 1.22.9 with Rancher 2.6.5. Approved.

**Comment by trinaths** [comment]
@samuelattwood  - Hi, what is the suggested way to update our README only in the charts submitted ? Do we need to follow the complete charts procedure again? Please share your suggestions.

**Pull request merged**
