### PR TITLE
Add External secrets operator -  v0.5.1

### PR DESCRIPTION
**Pull request by CharlKlein**
Good Day,

Please accept this PR for External Secrets Operator to be included in the Rancher Partner Charts.

Website : https://external-secrets.io/

**External Secrets Operator** is a Kubernetes operator that integrates external secret management systems like [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/), [HashiCorp Vault](https://www.vaultproject.io/), [Google Secrets Manager](https://cloud.google.com/secret-manager), [Azure Key Vault](https://azure.microsoft.com/en-us/services/key-vault/) and many more. 
The operator reads information from external APIs and automatically injects the values into a [Kubernetes Secret](https://kubernetes.io/docs/concepts/configuration/secret/).

Tested on Rancher 2.6.4

```
NAME                                                         READY   STATUS    RESTARTS   AGE
external-secrets-operator-7b485949b9-gzlj5                   1/1     Running   0          43s
external-secrets-operator-cert-controller-7588c6c6b8-245kt   1/1     Running   0          43s
external-secrets-operator-webhook-574cc89f8f-q26nx           1/1     Running   0          43s
```

Tagging a few of the Maintainers of ESO: @knelasevero @gusfcarvalho

### CODE REVIEW

**Comment by CharlKlein** [comment]
@samuelattwood, @alex-isv - Please Review :)

**Comment by samuelattwood** [comment]
Hey @CharlKlein 
Thanks for the submission. Everything looks good except your icon URL appears to be no longer valid. Possibly you meant for it to be [`https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-round-logo.svg`](https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-round-logo.svg)?

Aside from that I believe we are good to merge. Thanks

**Comment by CharlKlein** [comment]
> Hey @CharlKlein Thanks for the submission. Everything looks good except your icon URL appears to be no longer valid. Possibly you meant for it to be [`https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-round-logo.svg`](https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-round-logo.svg)?
> 
> Aside from that I believe we are good to merge. Thanks

Hi @samuelattwood, 

Thanks you. I have updated the Logo to the SVG one :) 

4 Files Changed:
- /index.yaml
- /charts/external-secrets-operator/external-secrets/0.5.100/Chart.yaml
- /charts/external-secrets-operator/external-secrets/0.5.100/README.md
- /charts/external-secrets-operator/external-secrets/0.5.100/README.md.gotmpl

**Comment by samuelattwood** [comment]
@CharlKlein Sorry for the delay.

Unfortunately just editing the links that way result in the gzip version of the chart not getting edited and differing from the version in the `charts` directory. The preffered option is to correct it with the standard `make prepare`, `make patch`, `make charts` process. 

```
$ export PACKAGE=external-secrets-operator
$ make prepare
Correct logo link in:
packages/external-secrets-operator/charts/Chart.yaml
packages/external-secrets-operator/charts/README.md
packages/external-secrets-operator/charts/README.md.gotmpl
$ make patch
$ make clean
$ git add packages/external-secrets-operator
$ git commit
$ make charts
$ git commit
```

Alternatively, it looks like your logo URL is corrected in your recent 0.5.2 release, so if you would like to just switch to that release you can avoid having to correct via the patch file. Thanks

**Comment by CharlKlein** [comment]
Hey @samuelattwoo. 

Thanks. I'll send a new PR in with v0.5.2 in the next few mins 😊

**Comment by samuelattwood** [comment]
@CharlKlein Sounds good, thanks. I should be able to review that one quickly :slightly_smiling_face:

**Comment by CharlKlein** [comment]
Closing this PR, Updated PR - #407

**Pull request closed without merging**
