### PR TITLE
Request to add gopaddle chart

### PR DESCRIPTION
**Pull request by gopaddle-io**

### CODE REVIEW

**Comment by samuelattwood** [comment]
Hey @gopaddle-io, it looks like you're trying to add two charts, which isn't a problem, but each chart should have a dedicated directory in `packages/gopaddle` with its own `upstream.yaml` - otherwise the CI tool won't be able to track updates for both charts.

**Comment by gopaddle-io** [comment]
@samuelattwood  @alex-isv We will remove the redundant chart. Is there any documentation that we could use to test the changes on an RKE cluster ?

**Comment by alex-isv** [comment]
> 
    Test modified chart (Required) 

*Before opening a pull request, you must test your helm chart on your local Rancher instance. 

From the 1st terminal, go to partner-charts directory and start your local http server 
#python3 -m http.server 8000 

From the 2nd terminal start ngrok ( https://ngrok.com/docs ) 
#ngrok http 8000 
That will expose your local http server for the test. 

Open your Rancher instance and go to Cluster Explorer -> Apps & Marketplace
From the top left select 'Chart repositories' and click Create
That will create your test repository. 
Copy ngrok url 
image




and paste into the url field and click 'Create'
Click on Charts and select your test chart 
You should be able to see your generated chart icon. 

Select your chart and install. 
It should be successfully deployed. 
Once you verified that there are no issues to deploy it from your Rancher instance, open a pull request.

**Comment by gopaddle-io** [comment]
@alex-isv We have followed the instructions and we are able to reproduce the issue. We are doing some qualifications on RKE2. We also see 2 charts in the listing. The reason being, we had used a chart name (gp-installer) in earlier releases and we had to rename the chart (gopaddle) in the recent releases. When we published our chart to ArtifactHub, the artifacthub-repo.yml had an option to ignore a few charts. Is it possible to ignore some charts like that in rancher partner charts ?

**Comment by alex-isv** [comment]
@gopaddle-io 
If you didn't release any versions, just hide the old one with a hidden true annotation. You can see in the workflow, a list of available variables > https://github.com/rancher/partner-charts#configuration-file

Featuring or Hiding a chart

Featuring and hiding charts is done by appending the catalog.cattle.io/featured or catalog.cattle.io/hidden chart annotation, respectively. The CI tool is able to perform these changes for you, to easly update the asset gzip, the charts directory, and the index.yaml.

If you open a PR after modifying an existing chart, the validation stage will expectedly fail, as the main goal is to ensure no accidental modification of already released charts.

In order to avoid this, somewhere in the title of the PR, include the string [modified charts]. This will cause the PR check to skip that part of the validation. For example, when you open the PR you could title it "Hiding suse/kubewarden-controller chart [modified charts]".

To view the currently featured charts

bin/partner-charts-ci feature list

To feature a chart

bin/partner-charts-ci feature add suse/kubewarden-controller 2

To remove the featured annotation

bin/partner-charts-ci feature remove suse/kubewarden-controller

To hide the chart

bin/partner-charts-ci hide suse/kubewarden-controller

After any of those changes, simply add, commit, push - and open a PR with "[modified charts]" in the title

git add index.yaml assets charts
git commit -m "Hiding suse/kubewarden-controller"
git push origin main-source

#Open a Pull Request

Is that what you are asking for?

**Comment by samuelattwood** [comment]
@gopaddle-io To clarify, is there a reason that the `gp-installer` chart should be present in this repo alongside the `gopaddle` chart or should it solely be the `gopaddle` chart? If we only want the `gopaddle` chart, then the current `upstream.yaml` looks correctly set to track only that chart.

**Comment by gopaddle-io** [comment]
@samuelattwood The Helm repo for gopaddle-lite package has two charts `gopaddle` and `gp-installer`. We intend to display only `gopaddle` chart in the Rancher marketplace and we cannot remove the `gp-installer` chart from our Helm repo as we have other sites referring to this chart name. We followed the guidelines stated by @alex-isv and added the `catalog.cattle.io/hidden: "true"` to the `charts/gopaddle/gp-installer/Chart.yaml`. This did not impact the listing ie., 2 charts were displayed in the Rancher UI. However when we added the annotation to the `index.yaml` in the root folder, it worked. We cannot add `Hidden` in the `upstream.yaml` as it will hide both the charts. Is it expected that we add the annotation to the `index.yaml' file ?

Coming to the feature list, we could add the gopaddle package to the feature list. But the gopaddle chart is not displayed in the featured list in the Rancher UI.
```sh
$ bin/partner-charts-ci feature add gopaddle/gopaddle-lite 4
$ bin/partner-charts-ci feature list
1: k10
2: cost-analyzer
3: nginx-ingress
4: gopaddle
```
Is this an expected behaviour ? Will this get resolved when we give a PR ?

On an additional note, we need a `default storageclass` in the cluster. Should we add the instructions to create and annotate the storageclass in our `README.md` file in the overlay folder ?

**Comment by gopaddle-io** [comment]
@nflondo Thanks for looking in to this. Looks like `bin/partner-charts-ci stage` is creating the charts folder and pulls both the gopaddle charts. We will try without the `ci` process. Regarding the `storageClass`, we will add the instructions in the `app-readme.md` file.

**Comment by gopaddle-io** [comment]
Hi, We have made the necessary changes and validated it. Would it be possible to merge it ?

**Comment by alex-isv** [comment]
Reviewed

**Review by alex-isv — APPROVED** [review]

**Pull request merged**
