### PR TITLE
Removes Chart.yaml.orig for dynatrace-oneagent-operator

### PR DESCRIPTION
**Pull request by 0sewa0**

### CODE REVIEW

**Comment by alex-isv** [comment]
@0sewa0 , you need to have all your files as in your old PR -> https://github.com/rancher/partner-charts/pull/253/files
since we didn't merge it to rancher main.
Pretty much the same with 2 commits, but no Chart.yaml.orig in the packages>overlay

**Comment by 0sewa0** [comment]
@alex-isv where do you want me to create this ? the old change is merged in `main-source` so I can't just re-add the same files to that branch.
do you want me to create a PR for `main` with the 2 commits (with this fix) ?

**Comment by alex-isv** [comment]
for the ref. -> https://github.com/rancher/partner-charts/pull/271

**Comment by samuelattwood** [comment]
@0sewa0 Feel free to close this PR out. https://github.com/rancher/partner-charts/pull/271 has been merged to purge the file. Your chart will be merged to `main` shortly. Thanks for the quick response.

**Pull request closed without merging**
