### PR TITLE
Submit Airlock Microgateway and Airlock Microgateway CNI

### PR DESCRIPTION
**Pull request by tyxeron**
Hi :wave: 

These two commits add the `Airlock Microgatway`  and  `Airlock Microgateway CNI` Helm charts.

Thanks for reviewing

GitHub Repo: https://github.com/airlock/microgateway

### CODE REVIEW

**Comment by recena** [comment]
📔 This contribution will be reviewed soon.

**Comment by troytop** [comment]
@tyxeron please see the email I sent regarding the SUSE Ready partner application. We'll review and merge the PR after that process is complete (and I'll update the README so this is clearer for others).

**Comment by adamkpickering** [comment]
The partner charts build tool (`partner-charts-ci`) does not provide a way to set kubernetes distribution specific Helm values. At the time that an upstream chart is processed for inclusion into the partner charts repo, `partner-charts-ci` does not have any info about what environment the chart will be installed into. To the best of my knowledge, your options are:

- Provide different charts for different environments. I don't recommend this, since this is not the typical way of doing things and it could confuse users.
- Have the users configure your application for the environment they are installing it into. [`questions.yml`](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps#additional-files-for-rancher-charts) may come in handy for this - you would add it as an overlay file. Alternatively the user can configure the application via `Values` as is usually done when installing a chart via `helm install`. The Rancher UI provides a way to do this without having to use the `helm` CLI tool.

I hope that helps :smile:

**Comment by tyxeron** [comment]
@adamkpickering Thanks for your reply :) I already have a questions.yml file so I hope that should be sufficient for the user to install it.

**Review by adamkpickering — COMMENTED** [review]
Looks good to me. However we are in the middle of a migration, so I am going to hold off on approval. We should have the migration completed in the next day or two.

**Review by adamkpickering — APPROVED** [review]

**Pull request merged**
