### PR TITLE
NGINX Service Mesh chart v1.4.0

### PR DESCRIPTION
**Pull request by pammecrandall**

### CODE REVIEW

**Comment by samuelattwood** [comment]
Hi @pammecrandall, your fork of the repo is quite behind and is encountering a few merge conflicts as a result. Please either rebase or merge upstream into your branch and resolve the conflicts. It may be easiest to simply revert to before your new commits, update your branch, and recreate the commits.

**Comment by pammecrandall** [comment]
Oh.  I should have seen that.  I've rebase it now.  Thank you!

**Review by samuelattwood — APPROVED** [review]
No worries, thanks for the update :slightly_smiling_face:

Looks good, tested on k3s 1.22.5 and RKE 1.21.6. Approved.

**Comment by pammecrandall** [comment]
Thank you!

**Pull request merged**
