### PR TITLE
(Citrix) adding citrix-adc-istio-ingress-gateway chart

### PR DESCRIPTION
**Pull request by ajeetas**

### CODE REVIEW

**Comment by ajeetas** [comment]
Can you please review the changes?

Regards,
Ajeeta Shakeet

**Review by PennyScissors — CHANGES_REQUESTED** [review]
Hello @ajeetas, this PR is adding a standard Helm chart, and it should be adding a package instead. Please refer to our guide [here](https://github.com/rancher/partner-charts/tree/main-source#readme) that explains the new process and workflow to add a package, and what's expected in the PR. Thanks

**Comment by ajeetas** [comment]
Hi PennyScissors,

I have added changes, can you please look into this.

Thanks,
Ajeeta

**Review by alex-isv — CHANGES_REQUESTED** [review]
Please review Workflow steps 1-8 -> https://github.com/rancher/partner-charts/tree/main-source#workflow
Verify that your structure looks correct.
Make sure that you can deploy it on a Marketplace from your local Rancher instance. (this is your responsibility to verify that it's working on Rancher)
Provide a screenshot of your installed helm chart from the Rancher.
It should look something like this >>
image

**Comment by ajeetas** [comment]
Hi Alex-isv,

I have updated changes and tested chart changes.

I have added a chart on fork of branch `https://github.com/rancher/charts` and added new template(v1.9.2) of charts on that branch also added this chart on `Chart Repositories` section on rancher to verify it. I am able to see my new template v1.9.2 and successfully done my testing for new changes (As shown in the pics).

**Comment by ajeetas** [comment]
Now I have added changes in fork of `https://github.com/rancher/partner-charts` this REPO and added that chart on rancher to verify changes but I have seen that chart is not visible there.
Can you please confirm me on this, why it’s lIke this ?
this is my repo `https://github.com/ajeetas/partner-charts` where I added my new template of the chart to test but I am not able to see this chart on rancher?


adding pics for more clarity:
rancher-5
rancher-6

**Comment by ajeetas** [comment]
Hi Alex-isv,

Following up on this PR, Any suggestion for me?

Thanks,
Ajeeta

**Comment by ajeetas** [comment]
Hi,

I have tried the below annotation:

annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/release-name: citrix-adc-istio-ingress-gateway
  catalog.cattle.io/display-name: citrix-adc-istio-ingress-gateway

Still, I am not able to see the chart on the rancher, can you please provide your suggestion on this? 

For testing I have added changes in this file:
https://github.com/ajeetas/partner-charts/blob/main/charts/citrix-adc-istio-ingress-gateway/citrix-adc-istio-ingress-gateway/v1.9.2/Chart.yaml
If this is the correct solution show the chart on the portal, I will update on current PR also.

Thanks,
Ajeeta

**Pull request closed without merging**
