### PR TITLE
New Trilio partner-chart k8s-triliovault-operator v2.0.0

### PR DESCRIPTION
**Pull request by bhagirathhapse**
PR consists of:

1. Chart file
2. app-readme.md
3. questions.yml
4. Required templates file

### CODE REVIEW

**Comment by PennyScissors** [comment]
Please update this PR to include your package only, which should contain your package.yaml, overlay directory with contents (if needed), and patch file (if needed), all in a single commit. Our drone will take care of building and publishing the assets once it's merged. If you have a patch file, make sure you save your changes in it and then clean the working directory as stated [here](https://github.com/rancher/partner-charts/tree/main-source#8-pull-request) before submitting a PR.

**Review by PennyScissors — CHANGES_REQUESTED** [review]
Please update this PR to include your package only, which should contain your package.yaml, overlay directory with contents (if needed), and patch file (if needed), all in a single commit. Our drone will take care of building and publishing the assets once it's merged. If you have a patch file, make sure you save your changes in it and then clean the working directory as stated here before submitting a PR.

**Comment by bhagirathhapse** [comment]
@PennyScissors Thank you for reviewing the PR, I appreciate the comments.
I have fixed the issues you have mentioned. Removed the unnecessary files and pushed the changes to this PR. Please review the change and let me know if everything looks good to merge.

**Comment by PennyScissors** [comment]
@bhagirathhapse I reviewed your changes and it's still missing some things, and including others that shouldn't be included. The PR should have 1 single commit, and only contain the files I mentioned in my previous comment. Please refer to our instructions [here](https://github.com/rancher/partner-charts/blob/main-source/README.md), and see [this PR](https://github.com/rancher/partner-charts/pull/68) as it is a good reference for what we expect in a PR submission. Thanks!

**Review by PennyScissors — COMMENTED** [review]
@bhagirathhapse I reviewed your changes and it's still missing some things, and including others that shouldn't be included. The PR should have 1 single commit, and only contain the files I mentioned in my previous comment. Please refer to our instructions [here](https://github.com/rancher/partner-charts/blob/main-source/README.md), and see [this PR](https://github.com/rancher/partner-charts/pull/68) as it is a good reference for what we expect in a PR submission. Thanks!

**Comment by bhagirathhapse** [comment]
Closing this PR  since we need to create new PR with above mentioned changes from Steven.

**Pull request closed without merging**
