### PR TITLE
Migrating Gluu flex chart

### PR DESCRIPTION
**Pull request by moabu**
This Pr migrates our flex chart to the new automated pathway.

### CODE REVIEW

**Comment by nflondo** [comment]
Hi @moabu,  PR #648 looks good!, except because of prior requirement to use a high patch version, the new chart version (5.0.10) is not recognized as the latest by Helm and Rancher UI does not display it at the top of the list (see this pic) 
gluu-out-order

To **fix** this, please add `PackageVersion: 01` to your `upstream.yaml` file e.g.:
```
…
DisplayName: Gluu Flex Cloud Identity and Access Management
PackageVersion: 03
ChartMetadata:
…
```
To **test** your new chart on Rancher Apps UI, follow these steps:
	1- If you haven't done so yet, pull down your new chart files into your local `partner-charts` repository.

> 		a. Get scripts by running: `scripts/pull-ci-scripts`
> 		b- List and find your company name/chart by running: `bin/partner-charts-ci list | grep <company>`
> 		c- set PACKAGE variable to your company/chart: `export PACKAGE=<company>/<chart-name> or export PACKAGE=<company>`
> 		d- run `bin/partner-charts-ci stage` or auto # the new charts should be downloaded

	
2- In your local "partner-charts" directory start a python3 http server:
`#python3 -m http.server 8000`
	3- From a second terminal expose your local http server via ngrok ( https://ngrok.com/download )
`#./ngrok http 8000`
	4- Create a test repository that points to your local `"partner-charts" `by  login in to Rancher UI, selecting a cluster and going to Apps > Repositories and clicking Create.
Enter a Name, copy ngrok forwarding url and paste into Target http(s) Index URL in Rancher UI and click 'Create' again.
	5- Once the new repository is "Active" go to "Apps > Charts" , find your new chart, review Readme is correct, etc. and install it.  It should be successfully deployed.
HTH

**Comment by moabu** [comment]
Hey @nflondo,

We are thinking due to the new structure change that we start from the latest chart. In other words, start as if we were coming in new. The mix between the old package version you guys had and whats actually out there is a little confusing so I think following the same structure now is better. At least now it will match the helm packages version. 

How would we go about that ? Remove everything related to gluu and then post with the latest chart in this PR ?

**Comment by moabu** [comment]
ok @nflondo all ready.

**Review by nflondo — APPROVED** [review]
Approved

**Pull request merged**
